package org.nmox.studio.application;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The markup-render law, carried across the l10n arc (v2.97.0).
 *
 * <p>A bundle value is the product's own authored sentence, so the
 * {@code Plain*} gates accept {@code Bundle.X(…)} where they would refuse
 * a bare variable. That trust holds only while the value's HEAD is the
 * product's own words: a value beginning with {@code {0}} puts an
 * ARGUMENT first, and an argument can be a file name, a project name, or
 * tool output beginning with {@code <html>} — which Swing would paint as
 * markup (the v1.208.0 class, closed product-wide in v2.86.0).
 *
 * <p>So: a key whose value starts with a placeholder is never handed
 * straight to a paint sink. It may still exist — inside a
 * {@code PlainText.plain(…)} / {@code PlainStatus.text(…)} wrapper, or in
 * an accessible name, which is spoken and never painted — but the direct
 * {@code new JLabel(Bundle.k(x))} shape is refused here.
 *
 * <p>The population is derived from the BUILT bundles (generated by the
 * annotation processor plus the hand-written ones), so a key added
 * tomorrow is covered without anyone remembering this file.
 */
class BundleHeadGateTest {

    private static final List<String> MODULES = List.of(
            "core", "editor", "tools", "project", "rack", "apiclient", "dbstudio", "web3", "infra", "ui");

    /** The paint sinks: text a user SEES, as opposed to hears. */
    private static final String SINKS =
            "new (?:javax\\.swing\\.)?J(?:Label|Button|CheckBox|RadioButton|MenuItem|ToggleButton)\\s*\\(\\s*"
            + "|\\.setToolTipText\\s*\\(\\s*"
            + "|\\.setText\\s*\\(\\s*"
            + "|setStatusText\\s*\\(\\s*";

    /** Every key whose value begins with a MessageFormat placeholder. */
    static Set<String> placeholderHeadKeys() throws IOException {
        Set<String> keys = new TreeSet<>();
        for (String module : MODULES) {
            for (String where : new String[] {"target/classes", "src/main"}) {
                Path root = Path.of("..", module, where);
                if (!Files.isDirectory(root)) {
                    continue;
                }
                try (Stream<Path> files = Files.walk(root)) {
                    for (Path p : files.filter(f -> f.getFileName().toString().equals("Bundle.properties")).toList()) {
                        Properties props = new Properties();
                        try (InputStream in = Files.newInputStream(p)) {
                            props.load(in);
                        }
                        for (String key : props.stringPropertyNames()) {
                            String value = props.getProperty(key, "");
                            if (value.startsWith("{") && value.length() > 1
                                    && Character.isDigit(value.charAt(1))) {
                                keys.add(key);
                            }
                        }
                    }
                }
            }
        }
        return keys;
    }

    @Test
    @DisplayName("no bundle key carries whitespace — such a key can never be looked up")
    void keysAreLookupable() throws IOException {
        // Found by the l10n arc (v2.97.0): rack's Quick Search bundle carried
        // "\\nQuickSearch/LiveRuns", whose key really began with a newline, so
        // the Running category's name had never resolved since it shipped.
        List<String> offenders = new ArrayList<>();
        for (String module : MODULES) {
            for (String where : new String[] {"target/classes", "src/main"}) {
                Path root = Path.of("..", module, where);
                if (!Files.isDirectory(root)) {
                    continue;
                }
                try (Stream<Path> files = Files.walk(root)) {
                    for (Path p : files.filter(f -> f.getFileName().toString().startsWith("Bundle")
                            && f.getFileName().toString().endsWith(".properties")).toList()) {
                        Properties props = new Properties();
                        try (InputStream in = Files.newInputStream(p)) {
                            props.load(in);
                        }
                        for (String key : props.stringPropertyNames()) {
                            if (!key.equals(key.strip()) || key.chars().anyMatch(Character::isWhitespace)) {
                                offenders.add(module + " " + p.getFileName() + ": " + key.strip());
                            }
                        }
                    }
                }
            }
        }
        assertThat(offenders).as("keys with whitespace — the lookup can never match them").isEmpty();
    }

    @Test
    @DisplayName("no bundle value that begins with a placeholder is painted straight into a Swing sink")
    void placeholderHeadNeverPainted() throws IOException {
        Set<String> risky = placeholderHeadKeys();
        assertThat(risky).as("the arc produced keys with a placeholder head — the population this gate guards")
                .isNotEmpty();
        Pattern painted = Pattern.compile("(?:" + SINKS + ")Bundle\\.(" + String.join("|", risky) + ")\\s*\\(");
        List<String> offenders = new ArrayList<>();
        for (String module : MODULES) {
            Path src = Path.of("..", module, "src", "main", "java");
            if (!Files.isDirectory(src)) {
                continue;
            }
            try (Stream<Path> files = Files.walk(src)) {
                for (Path p : files.filter(f -> f.toString().endsWith(".java")).toList()) {
                    String body = Files.readString(p);
                    Matcher m = painted.matcher(body);
                    while (m.find()) {
                        int line = 1 + (int) body.chars().limit(m.start()).filter(c -> c == '\n').count();
                        offenders.add(module + "/" + p.getFileName() + ":" + line + " Bundle." + m.group(1));
                    }
                }
            }
        }
        assertThat(offenders).as(
                "a placeholder-headed value painted directly — wrap it in PlainText.plain(…) or reword the value "
                + "so the product's own words come first")
                .isEmpty();
    }
}
