package org.nmox.studio.application;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.jar.JarFile;
import java.util.stream.Stream;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.nmox.studio.application.VsCodeChordTable.Os;
import org.nmox.studio.application.VsCodeChordTable.Row;
import org.nmox.studio.application.VsCodeChordTable.Scope;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

/**
 * The generator of the sixth keymap profile, <b>VS Code</b>.
 *
 * <p><b>What a new profile inherits, measured</b> (RELEASE310 bytecode, not
 * folklore). The two halves of a profile answer differently:
 * <ul>
 *   <li><b>Global</b> ({@code org.netbeans.core.NbKeymap.bindings()}, and
 *       {@code LayersBridge.getKeymap} for the Options dialog): the
 *       {@code Shortcuts} folder, then {@code Keymaps/<profile>} over it by
 *       file name. A new profile therefore starts with everything modules
 *       register in {@code Shortcuts} and with NOTHING of
 *       {@code Keymaps/NetBeans}: Save, Copy, Close, Find, the debugger's
 *       stepping keys and the product's own window chords all live there.</li>
 *   <li><b>Editor</b> ({@code SettingsType$DefaultLocator.addModulesFiles}):
 *       with a profile named, the storage reads
 *       {@code Editors[/mime]/Keybindings/<profile>/Defaults} and no other
 *       folder. No profile falls back to another: a new one starts EMPTY, down
 *       to the arrow keys and Enter (which is why the platform's own Idea and
 *       Eclipse files spell out {@code caret-backward} and
 *       {@code insert-break}).</li>
 * </ul>
 * So the VS Code profile is generated, not hand-written: <i>the default
 * profile's bindings, as the assembled cluster resolves them on each OS, with
 * {@code scripts/vscode-keymap/chords.txt} laid over them</i>. Every default
 * binding a VS Code chord lands on is displaced; it survives on whatever
 * other chord it has, and {@code displaced.txt} says which were left with
 * none. A platform upgrade that changes the default profile changes what this
 * produces, and {@link VsCodeKeymapResolutionTest} fails until
 * {@code scripts/generate-vscode-keymap.sh} has been run again.
 *
 * <p><b>Where the output goes.</b> Two regions of the ui module's layer,
 * between marker comments ({@code Keymaps/VSCode}, and an {@code Editors}
 * folder registering the keybinding files), and the keybinding files in
 * {@code org/nmox/studio/ui/keymap}. The editor half is written the way the
 * platform writes its own profiles: one file for every OS (what Windows
 * resolves), then a file the layer targets at macOS and one at Linux that
 * remove and add what differs there. Every key is spelled with explicit
 * modifiers, so a file means the same keystrokes whichever OS reads it.
 *
 * <p><b>What the files cannot make the platform warn about</b> (each warning
 * read from the code that logs it): a keybinding file is a module file of a
 * profile whose folder is not named NetBeans, so
 * {@code KeyMapsStorage$KeyMapsReader}'s "A or C in the default profile"
 * warning does not apply, no key is bound twice in one file and every bind
 * has an action; every shadow names an action that exists in the cluster
 * ({@code LayersBridge} logs "Invalid shortcut" for one that does not), every
 * file name parses as a keystroke, and no single keystroke is bound on the
 * first stroke of a two-stroke chord ({@code NbKeymap} logs the conflict and
 * drops the chord).
 */
final class VsCodeKeymapProfile {

    static final String PROFILE = "VSCode";
    static final String DEFAULT_PROFILE = "NetBeans";

    static final Path CLUSTER = Path.of("target", "nmoxstudio");
    static final Path UI_RESOURCES = Path.of("..", "ui", "src", "main", "resources", "org", "nmox", "studio", "ui");
    static final Path UI_LAYER = UI_RESOURCES.resolve("layer.xml");
    static final Path DISPLACED = Path.of("..", "scripts", "vscode-keymap", "displaced.txt");
    /** The folder, beside the ui layer, that holds the generated keybinding files. */
    static final String FILES_DIR = "keymap";
    static final String NAMES_BUNDLE = "org.nmox.studio.ui.keymap.names.Bundle";

    static final String GLOBAL_BEGIN = "<!-- vscode-keymap:global BEGIN - generated by scripts/generate-vscode-keymap.sh, do not edit -->";
    static final String GLOBAL_END = "<!-- vscode-keymap:global END -->";
    static final String EDITORS_BEGIN = "<!-- vscode-keymap:editors BEGIN - generated by scripts/generate-vscode-keymap.sh, do not edit -->";
    static final String EDITORS_END = "<!-- vscode-keymap:editors END -->";

    // ---- the cluster, as the system filesystem merges it -----------------

    /** A file of the merged layers: its {@code originalFile} ("method:…" for a methodvalue) and its flags. */
    record LayerFile(String original, boolean nmoxShortcut) {
    }

    record Bind(String key, String action, boolean remove) {
    }

    /** One editor keybinding file as a layer registers it. */
    record KeybindingFile(String folder, String name, Integer position, String targetOs, int order, List<Bind> binds) {
    }

    /** Everything the generator reads: the merged layer files and every editor keybinding file. */
    static final class Cluster {

        final Map<String, Map<String, LayerFile>> files = new LinkedHashMap<>();
        final Map<String, Set<String>> masks = new LinkedHashMap<>();
        final List<KeybindingFile> keybindings = new ArrayList<>();

        Map<String, LayerFile> visible(String folder) {
            Map<String, LayerFile> out = new LinkedHashMap<>(files.getOrDefault(folder, Map.of()));
            out.keySet().removeAll(masks.getOrDefault(folder, Set.of()));
            return out;
        }

        boolean exists(String path) {
            int slash = path.lastIndexOf('/');
            return slash > 0 && visible(path.substring(0, slash)).containsKey(path.substring(slash + 1));
        }

        /** The mimes ("" is the base every editor shares) that register keybindings for a profile. */
        Set<String> mimes(String profile) {
            Set<String> out = new TreeSet<>();
            String tail = "/Keybindings/" + profile + "/Defaults";
            for (KeybindingFile f : keybindings) {
                if (f.folder().equals("Editors" + tail)) {
                    out.add("");
                } else if (f.folder().startsWith("Editors/") && f.folder().endsWith(tail)) {
                    out.add(f.folder().substring("Editors/".length(), f.folder().length() - tail.length()));
                }
            }
            return out;
        }

        /**
         * What one folder of keybinding files resolves to on an OS, the way
         * {@code StorageImpl._load} merges it: files in
         * {@code FileUtil.getOrder} order, one skipped when its
         * {@code nbeditor-settings-targetOS} names another OS, each file's
         * removals applied before its bindings.
         */
        Map<List<String>, String> effective(String profile, String mime, Os os) {
            String folder = "Editors/" + (mime.isEmpty() ? "" : mime + "/") + "Keybindings/" + profile + "/Defaults";
            Set<String> hidden = masks.getOrDefault(folder, Set.of());
            List<KeybindingFile> in = new ArrayList<>();
            for (KeybindingFile f : keybindings) {
                if (f.folder().equals(folder) && !hidden.contains(f.name()) && appliesOn(f.targetOs(), os)) {
                    in.add(f);
                }
            }
            in.sort(Comparator.<KeybindingFile>comparingInt(f -> f.position() == null ? Integer.MIN_VALUE : f.position())
                    .thenComparingInt(f -> f.position() == null ? f.order() : 0)
                    .thenComparing(KeybindingFile::name));
            Map<List<String>, String> out = new LinkedHashMap<>();
            for (KeybindingFile f : in) {
                for (Bind b : f.binds()) {
                    if (b.remove()) {
                        out.remove(strokes(b.key(), os));
                    }
                }
                for (Bind b : f.binds()) {
                    if (!b.remove() && b.action() != null) {
                        List<String> seq = strokes(b.key(), os);
                        if (seq != null) {
                            out.put(seq, b.action());
                        }
                    }
                }
            }
            return out;
        }
    }

    /**
     * {@code SettingsType$DefaultLocator.isApplicableForThisTargetOs}: the
     * attribute names a {@code BaseUtilities} field whose bits must meet the
     * running OS. The two the cluster uses are modelled; another fails the
     * generator rather than being guessed.
     */
    static boolean appliesOn(String targetOs, Os os) {
        if (targetOs == null || targetOs.isEmpty()) {
            return true;
        }
        return switch (targetOs) {
            case "OS_MAC" -> os == Os.MAC;
            case "OS_LINUX" -> os == Os.LINUX;
            default -> throw new IllegalStateException("a keybinding file targets " + targetOs
                    + ", which the generator does not model");
        };
    }

    static Cluster load() throws Exception {
        Cluster c = new Cluster();
        List<Path> jars;
        try (Stream<Path> s = Files.walk(CLUSTER)) {
            jars = s.filter(p -> {
                String n = p.toString().replace('\\', '/');
                return n.endsWith(".jar") && n.contains("/modules/") && !n.contains("/ext/") && !n.contains("/locale/");
            }).sorted(Comparator.comparing(p -> p.toString().replace('\\', '/'))).toList();
        }
        int[] order = {0};
        for (Path jar : jars) {
            try (JarFile jf = new JarFile(jar.toFile())) {
                List<String> layers = new ArrayList<>();
                if (jf.getEntry("META-INF/generated-layer.xml") != null) {
                    layers.add("META-INF/generated-layer.xml");
                }
                String declared = jf.getManifest() == null ? null
                        : jf.getManifest().getMainAttributes().getValue("OpenIDE-Module-Layer");
                if (declared != null && jf.getEntry(declared) != null) {
                    layers.add(declared);
                }
                for (String layer : layers) {
                    Element root = parse(jf, layer);
                    if (root != null) {
                        walk(c, jf, layer, root, "", order);
                    }
                }
            } catch (java.util.zip.ZipException notAJar) {
                // a non-jar artefact in a modules dir is not the generator's business
            }
        }
        if (!c.files.containsKey("Shortcuts") || !c.files.containsKey("Keymaps/" + DEFAULT_PROFILE)) {
            throw new IllegalStateException("the assembled cluster was not read: no Shortcuts or Keymaps/" + DEFAULT_PROFILE
                    + " under " + CLUSTER.toAbsolutePath() + " (run after package)");
        }
        return c;
    }

    private static Element parse(JarFile jf, String entry) throws Exception {
        DocumentBuilderFactory f = DocumentBuilderFactory.newInstance();
        f.setValidating(false);
        f.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        DocumentBuilder b = f.newDocumentBuilder();
        // an external entity beside the layer (the defaults module's Eclipse keymap) is read
        // from the jar; every other system id resolves to nothing, never to the network
        b.setEntityResolver((publicId, systemId) -> {
            String name = systemId.substring(systemId.lastIndexOf('/') + 1);
            String dir = entry.contains("/") ? entry.substring(0, entry.lastIndexOf('/') + 1) : "";
            var e = jf.getEntry(dir + name);
            if (e != null && name.endsWith(".xml")) {
                return new InputSource(jf.getInputStream(e));
            }
            return new InputSource(new ByteArrayInputStream(new byte[0]));
        });
        try (InputStream in = jf.getInputStream(jf.getEntry(entry))) {
            return b.parse(in).getDocumentElement();
        } catch (org.xml.sax.SAXException unreadable) {
            return null;
        }
    }

    private static void walk(Cluster c, JarFile jf, String layer, Element folder, String path, int[] order)
            throws Exception {
        NodeList kids = folder.getChildNodes();
        for (int i = 0; i < kids.getLength(); i++) {
            Node n = kids.item(i);
            if (!(n instanceof Element e)) {
                continue;
            }
            String name = e.getAttribute("name");
            if ("folder".equals(e.getTagName())) {
                walk(c, jf, layer, e, path.isEmpty() ? name : path + "/" + name, order);
            } else if ("file".equals(e.getTagName())) {
                if (name.endsWith("_hidden")) {
                    c.masks.computeIfAbsent(path, k -> new LinkedHashSet<>())
                            .add(name.substring(0, name.length() - "_hidden".length()));
                    continue;
                }
                Map<String, String> attrs = attrs(e);
                c.files.computeIfAbsent(path, k -> new LinkedHashMap<>())
                        .put(name, new LayerFile(attrs.getOrDefault("originalFile", ""), "true".equals(attrs.get("nmoxShortcut"))));
                if (path.contains("/Keybindings/") && !e.getAttribute("url").isEmpty()) {
                    List<Bind> binds = binds(jf, layer, e.getAttribute("url"));
                    if (binds != null) {
                        String pos = attrs.get("position");
                        c.keybindings.add(new KeybindingFile(path, name, pos == null ? null : Integer.valueOf(pos),
                                attrs.getOrDefault("nbeditor-settings-targetOS", ""), order[0]++, binds));
                    }
                }
            }
        }
    }

    /** A file's own attributes; a methodvalue is kept as "method:…" so it is never mistaken for a path. */
    private static Map<String, String> attrs(Element file) {
        Map<String, String> out = new LinkedHashMap<>();
        NodeList kids = file.getChildNodes();
        for (int i = 0; i < kids.getLength(); i++) {
            if (kids.item(i) instanceof Element a && "attr".equals(a.getTagName())) {
                String value = a.hasAttribute("stringvalue") ? a.getAttribute("stringvalue")
                        : a.hasAttribute("intvalue") ? a.getAttribute("intvalue")
                        : a.hasAttribute("boolvalue") ? a.getAttribute("boolvalue")
                        : a.hasAttribute("methodvalue") ? "method:" + a.getAttribute("methodvalue") : "";
                out.put(a.getAttribute("name"), value);
            }
        }
        return out;
    }

    private static List<Bind> binds(JarFile jf, String layer, String url) throws Exception {
        String entry;
        if (url.startsWith("nbres:") || url.startsWith("nbresloc:")) {
            entry = url.substring(url.indexOf(':') + 1).replaceFirst("^/+", "");
        } else {
            String dir = layer.contains("/") ? layer.substring(0, layer.lastIndexOf('/') + 1) : "";
            entry = Path.of(dir + url).normalize().toString().replace('\\', '/');
        }
        if (jf.getEntry(entry) == null) {
            return null;
        }
        Element root = parse(jf, entry);
        if (root == null) {
            return null;
        }
        List<Bind> out = new ArrayList<>();
        NodeList binds = root.getElementsByTagName("bind");
        for (int i = 0; i < binds.getLength(); i++) {
            Element b = (Element) binds.item(i);
            out.add(new Bind(b.getAttribute("key"), b.hasAttribute("actionName") ? b.getAttribute("actionName") : null,
                    Boolean.parseBoolean(b.getAttribute("remove"))));
        }
        return out;
    }

    // ---- the platform's keystroke notation --------------------------------

    /**
     * A key name as the platform writes it ({@code DS-P}, {@code O-Enter},
     * and {@code D-U U} or {@code D-U$U} for two strokes) to the strokes one
     * OS presses, the whole of {@code Utilities.stringToKey} (read from its
     * bytecode): {@code D} is Cmd on macOS and Ctrl elsewhere, {@code O} is
     * Ctrl on macOS and Alt elsewhere - and where macOS keeps the Cmd chord
     * for itself ({@code usableKeyOnMac}: any Cmd with Q, Cmd alone with H,
     * Space or Tab, Cmd+Opt with D, Ctrl+Cmd with Space) {@code D} becomes
     * Ctrl, or Opt when the name also carries {@code O}. Null for a name
     * that is not a keystroke.
     */
    static List<String> strokes(String name, Os os) {
        List<String> out = new ArrayList<>();
        for (String token : name.replace('$', ' ').trim().split("\\s+")) {
            String s = stroke(token, os);
            if (s == null) {
                return null;
            }
            out.add(s);
        }
        return out;
    }

    private static String stroke(String token, Os os) {
        String up = token.toUpperCase(Locale.ENGLISH);
        int dash = up.lastIndexOf('-');
        // stringToKey tokenizes on '-', so "O-S-F9" is O and S on F9: dashes inside the modifiers are separators
        String mods = dash > 0 ? up.substring(0, dash).replace("-", "") : "";
        String key = dash > 0 ? up.substring(dash + 1) : up;
        if (key.isEmpty()) {
            return null;
        }
        boolean mac = os == Os.MAC;
        boolean wild = false;
        boolean altWild = false;
        Set<String> m = new TreeSet<>();
        for (char c : mods.toCharArray()) {
            switch (c) {
                case 'C' -> m.add("ctrl");
                case 'A' -> m.add("alt");
                case 'S' -> m.add("shift");
                case 'M' -> m.add("meta");
                case 'D' -> wild = true;
                case 'O' -> altWild = true;
                default -> {
                    return null;
                }
            }
        }
        if (wild) {
            if (!mac) {
                m.add("ctrl");
            } else {
                Set<String> probe = new TreeSet<>(m);
                probe.add("meta");
                if (altWild) {
                    probe.add("ctrl");
                }
                if (usableOnMac(key, probe)) {
                    m.add("meta");
                } else {
                    m.add(altWild ? "alt" : "ctrl");
                }
            }
        }
        if (altWild) {
            m.add(mac ? "ctrl" : "alt");
        }
        return String.join("+", m) + "|" + key;
    }

    private static boolean usableOnMac(String key, Set<String> mods) {
        if (key.equals("Q")) {
            return false;
        }
        if (mods.equals(Set.of("meta"))) {
            return !Set.of("H", "SPACE", "TAB").contains(key);
        }
        if (key.equals("D") && mods.contains("meta") && mods.contains("alt")) {
            return false;
        }
        return !(key.equals("SPACE") && mods.contains("meta") && mods.contains("ctrl"));
    }

    // ---- the generator ----------------------------------------------------

    /** What was generated: the two layer regions, the keybinding files by name, and the displaced report. */
    record Output(String globalRegion, String editorsRegion, Map<String, String> files, String displaced) {
    }

    private static final class Claims {

        /** per OS: every chord a row claims, with the rows that claim it. */
        final Map<Os, Map<List<String>, List<Row>>> all = new EnumMap<>(Os.class);

        Claims(List<Row> rows) {
            for (Os os : Os.values()) {
                all.put(os, new LinkedHashMap<>());
            }
            for (Row r : rows) {
                r.chords().forEach((os, seq) -> all.get(os).computeIfAbsent(seq, k -> new ArrayList<>()).add(r));
            }
        }

        /** The rows whose chord on this OS is {@code seq}, or begins it, or is begun by it. */
        List<Row> colliding(Os os, List<String> seq, boolean globalRowsAndPrefixesOnly) {
            List<Row> out = new ArrayList<>();
            all.get(os).forEach((claimed, rows) -> {
                if (!VsCodeChordTable.collide(claimed, seq)) {
                    return;
                }
                for (Row r : rows) {
                    // an editor row leaves the global keymap alone (VS Code scopes it to a focused
                    // editor), except that the first stroke of its two-stroke chord must stay free
                    boolean prefixOnly = claimed.size() > seq.size();
                    if (!globalRowsAndPrefixesOnly || r.scope() == Scope.GLOBAL || prefixOnly) {
                        out.add(r);
                    }
                }
            });
            return out;
        }
    }

    static Output generate(Cluster cluster, List<Row> rows) {
        Claims claims = new Claims(rows);
        List<String> lost = new ArrayList<>();
        checkRows(cluster, rows);

        // ---- the editor half
        Set<String> mimes = cluster.mimes(DEFAULT_PROFILE);
        mimes.add("");
        rows.forEach(r -> mimes.addAll(r.variants().keySet()));
        Map<String, Map<Os, Map<List<String>, String>>> editor = new TreeMap<>();
        for (String mime : mimes) {
            Map<Os, Map<List<String>, String>> perOs = new EnumMap<>(Os.class);
            for (Os os : Os.values()) {
                Map<List<String>, String> out = new LinkedHashMap<>();
                cluster.effective(DEFAULT_PROFILE, mime, os).forEach((seq, action) -> {
                    List<Row> taken = claims.colliding(os, seq, false);
                    if (taken.isEmpty()) {
                        out.put(seq, action);
                        return;
                    }
                    boolean same = taken.stream().anyMatch(r -> r.scope() == Scope.EDITOR
                            && seq.equals(r.chords().get(os)) && action.equals(r.targetFor(mime)));
                    if (!same) {
                        lost.add("editor" + (mime.isEmpty() ? "" : " " + mime) + " | " + os + " | " + spell(seq, " ")
                                + " | " + action + " | " + taken.get(0).command());
                    }
                });
                for (Row r : rows) {
                    List<String> seq = r.chords().get(os);
                    if (r.scope() != Scope.EDITOR || !r.bound() || seq == null) {
                        continue;
                    }
                    if (mime.isEmpty()) {
                        out.put(seq, r.target());
                    } else if (r.variants().containsKey(mime)) {
                        out.put(seq, r.variants().get(mime));
                    }
                }
                perOs.put(os, out);
            }
            editor.put(mime, perOs);
        }
        // a language's own binding that says what the base already says is not written twice
        Map<Os, Map<List<String>, String>> base = editor.get("");
        editor.forEach((mime, perOs) -> {
            if (!mime.isEmpty()) {
                perOs.forEach((os, map) -> map.entrySet()
                        .removeIf(e -> e.getValue().equals(base.get(os).get(e.getKey()))));
            }
        });

        Map<String, String> files = new TreeMap<>();
        StringBuilder editors = new StringBuilder();
        editors.append("    ").append(EDITORS_BEGIN).append('\n');
        editors.append("    <folder name=\"Editors\">\n");
        Map<String, List<String[]>> registered = new TreeMap<>();
        for (Map.Entry<String, Map<Os, Map<List<String>, String>>> e : editor.entrySet()) {
            String mime = e.getKey();
            String stem = "vscode-profile" + (mime.isEmpty() ? "" : "." + mime.replace('/', '.'));
            Map<List<String>, String> everywhere = e.getValue().get(Os.WINDOWS);
            List<String[]> entries = new ArrayList<>();
            if (!everywhere.isEmpty()) {
                files.put(stem + ".xml", keybindingFile(Map.of(), everywhere, "every OS; what Windows resolves"));
                entries.add(new String[] {"nmox-vscode-profile.xml", stem + ".xml", "100", ""});
            }
            for (Os os : List.of(Os.MAC, Os.LINUX)) {
                Map<List<String>, String> here = e.getValue().get(os);
                Map<List<String>, String> gone = new LinkedHashMap<>();
                everywhere.forEach((seq, action) -> {
                    if (!here.containsKey(seq)) {
                        gone.put(seq, action);
                    }
                });
                Map<List<String>, String> added = new LinkedHashMap<>();
                here.forEach((seq, action) -> {
                    if (!action.equals(everywhere.get(seq))) {
                        added.put(seq, action);
                    }
                });
                if (!gone.isEmpty() || !added.isEmpty()) {
                    String suffix = os == Os.MAC ? "-mac" : "-linux";
                    files.put(stem + suffix + ".xml", keybindingFile(gone, added,
                            (os == Os.MAC ? "macOS" : "Linux") + ": what differs from the every-OS file"));
                    entries.add(new String[] {"nmox-vscode-profile" + suffix + ".xml", stem + suffix + ".xml",
                            os == Os.MAC ? "200" : "300", os == Os.MAC ? "OS_MAC" : "OS_LINUX"});
                }
            }
            if (!entries.isEmpty() || mime.isEmpty()) {
                registered.put(mime, entries);
            }
        }
        writeEditors(editors, registered);
        editors.append("    </folder>\n");
        editors.append("    ").append(EDITORS_END).append('\n');

        // ---- the global half
        Map<String, LayerFile> shadows = new TreeMap<>();
        for (Row r : rows) {
            if (r.scope() != Scope.GLOBAL || !r.bound()) {
                continue;
            }
            String name = globalName(r) + ".shadow";
            LayerFile before = shadows.put(name, new LayerFile(r.target(), true));
            if (before != null && !before.original().equals(r.target())) {
                throw new IllegalStateException(r + ": " + name + " is already bound to " + before.original());
            }
        }
        Map<Os, Map<String, List<String[]>>> defaults = defaultGlobals(cluster);
        cluster.visible("Keymaps/" + DEFAULT_PROFILE).forEach((name, file) -> {
            if (!name.endsWith(".shadow")) {
                return;
            }
            String key = name.substring(0, name.length() - ".shadow".length());
            if (file.original().startsWith("method:")) {
                lost.add("global Keymaps | every OS | " + key + " | " + file.original()
                        + " | not inherited: its target is decided by a method at run time");
                return;
            }
            if (!cluster.exists(file.original())) {
                lost.add("global Keymaps | every OS | " + key + " | " + file.original()
                        + " | not inherited: no module in this cluster registers the action");
                return;
            }
            // a default binding a row meets is not inherited: it was taken, or it is the row's own shadow
            if (meetsGlobally(claims, key, file.original(), "global Keymaps", lost, defaults) == Meets.NOTHING
                    && !hasName(shadows, key)) {
                shadows.put(name, new LayerFile(file.original(), file.nmoxShortcut()));
            }
        });
        Set<String> removed = new TreeSet<>();
        cluster.visible("Shortcuts").forEach((name, file) -> {
            if (!name.endsWith(".shadow")) {
                return;
            }
            String key = name.substring(0, name.length() - ".shadow".length());
            // Shortcuts reaches every profile: one a row takes is dropped by name, unless the
            // row's own shadow carries that name and so replaces it
            if (meetsGlobally(claims, key, file.original(), "global Shortcuts", lost, defaults) == Meets.TAKEN
                    && !hasName(shadows, key)) {
                removed.add(key + ".removed");
            }
        });
        checkPrefixes(cluster, shadows, removed);

        StringBuilder global = new StringBuilder();
        global.append("        ").append(GLOBAL_BEGIN).append('\n');
        global.append("        <folder name=\"").append(PROFILE).append("\">\n");
        global.append("            <attr name=\"SystemFileSystem.localizingBundle\" stringvalue=\"").append(NAMES_BUNDLE)
                .append("\"/>\n");
        shadows.forEach((name, file) -> {
            global.append("            <file name=\"").append(xml(name)).append("\">\n");
            global.append("                <attr name=\"originalFile\" stringvalue=\"").append(xml(file.original()))
                    .append("\"/>\n");
            if (file.nmoxShortcut()) {
                global.append("                <attr name=\"nmoxShortcut\" boolvalue=\"true\"/>\n");
            }
            global.append("            </file>\n");
        });
        removed.forEach(name -> global.append("            <file name=\"").append(xml(name)).append("\"/>\n"));
        global.append("        </folder>\n");
        global.append("        ").append(GLOBAL_END).append('\n');

        return new Output(global.toString(), editors.toString(), files, report(lost, editor, shadows, cluster, removed));
    }

    /** The file of a row's shadow: the one name that is the row's chord on every OS it names. */
    static String globalName(Row r) {
        List<String> mac = r.chords().get(Os.MAC);
        List<String> win = r.chords().get(Os.WINDOWS);
        List<String> linux = r.chords().get(Os.LINUX);
        if (win == null ? linux != null : !win.equals(linux)) {
            throw new IllegalStateException(r + ": a Keymaps shadow cannot differ between Windows and Linux");
        }
        if (mac == null) {
            throw new IllegalStateException(r + ": a Keymaps shadow cannot be bound on Windows and Linux only"
                    + " - every modifier a PC sends, a Mac sends too");
        }
        String name;
        if (win == null) {
            if (!mac.get(0).contains("meta")) {
                throw new IllegalStateException(r + ": a macOS-only shadow needs Cmd in its first stroke,"
                        + " the one modifier a PC keyboard does not send");
            }
            name = spell(mac, " ");
        } else if (mac.equals(win)) {
            name = spell(mac, " ");
        } else {
            if (mac.size() != win.size()) {
                throw new IllegalStateException(r + ": the macOS and Windows chords have different lengths");
            }
            List<String> strokes = new ArrayList<>();
            for (int i = 0; i < mac.size(); i++) {
                String m = mac.get(i);
                String w = win.get(i);
                if (m.equals(w)) {
                    strokes.add(VsCodeChordTable.spell(m));
                    continue;
                }
                Set<String> mm = mods(m);
                Set<String> wm = mods(w);
                boolean twin = key(m).equals(key(w)) && mm.remove("meta") && wm.remove("ctrl")
                        && !mm.contains("ctrl") && !wm.contains("meta") && mm.equals(wm);
                if (!twin) {
                    throw new IllegalStateException(r + ": the macOS and Windows chords are neither the same keys"
                            + " nor the Cmd/Ctrl twin - a Keymaps shadow can say nothing else");
                }
                strokes.add("D" + (mm.contains("alt") ? "A" : "") + (mm.contains("shift") ? "S" : "") + "-" + key(m));
            }
            name = String.join(" ", strokes);
        }
        for (Os os : Os.values()) {
            List<String> want = r.chords().get(os);
            if (want != null && !want.equals(strokes(name, os))) {
                throw new IllegalStateException(r + ": " + name + " resolves to " + strokes(name, os) + " on " + os
                        + ", not " + want + " (a chord macOS keeps for itself?)");
            }
        }
        return name;
    }

    private static Set<String> mods(String stroke) {
        Set<String> m = new TreeSet<>(List.of(stroke.substring(0, stroke.indexOf('|')).split("\\+")));
        m.remove("");
        return m;
    }

    private static String key(String stroke) {
        return stroke.substring(stroke.indexOf('|') + 1);
    }

    private static boolean hasName(Map<String, LayerFile> shadows, String key) {
        String up = key.toUpperCase(Locale.ROOT);
        return shadows.keySet().stream().anyMatch(n -> n.substring(0, n.length() - ".shadow".length())
                .toUpperCase(Locale.ROOT).equals(up));
    }

    /** How a default global binding meets the table: untouched, already what a row binds, or taken by a row. */
    private enum Meets { NOTHING, THE_SAME, TAKEN }

    /**
     * Whether a row takes a default global binding's keystroke on some OS,
     * recording what it displaces. A shadow file serves every OS, so one taken
     * on any OS is dropped on all of them, and the report says so for the
     * others. Where the default profile itself already answers the keystroke
     * with the row's own action through another file (the platform's own
     * two-names-one-keystroke ambiguity, such as the Terminal's Find beside
     * Find in Projects on Ctrl+Shift+F), the row changes nothing there and the
     * entry is left as the default profile has it.
     */
    private static Meets meetsGlobally(Claims claims, String key, String original, String where, List<String> lost,
            Map<Os, Map<String, List<String[]>>> defaults) {
        Meets out = Meets.NOTHING;
        Set<Os> quiet = new TreeSet<>();
        List<String> here = new ArrayList<>();
        for (Os os : Os.values()) {
            List<String> seq = strokes(key, os);
            if (seq == null) {
                continue;
            }
            boolean met = false;
            for (Row r : claims.colliding(os, seq, true)) {
                met = true;
                boolean same = r.scope() == Scope.GLOBAL && seq.equals(r.chords().get(os))
                        && (original.equals(r.target()) || defaultAnswers(defaults, os, seq, key, r.target()));
                if (same) {
                    out = out == Meets.NOTHING ? Meets.THE_SAME : out;
                } else {
                    out = Meets.TAKEN;
                    here.add(where + " | " + os + " | " + key + " | " + original + " | " + r.command());
                }
            }
            if (!met) {
                quiet.add(os);
            }
        }
        lost.addAll(here);
        if (out == Meets.TAKEN) {
            for (Os os : quiet) {
                if (strokes(key, os) != null) {
                    lost.add(where + " | " + os + " | " + key + " | " + original
                            + " | (taken on another OS: one file serves every OS)");
                }
            }
        }
        return out;
    }

    /** Whether another default binding than {@code key} already fires {@code target} on {@code seq}. */
    private static boolean defaultAnswers(Map<Os, Map<String, List<String[]>>> defaults, Os os, List<String> seq,
            String key, String target) {
        for (String[] b : defaults.get(os).getOrDefault(String.join(" ", seq), List.of())) {
            if (!b[0].equalsIgnoreCase(key) && b[1].equals(target)) {
                return true;
            }
        }
        return false;
    }

    /** The default profile's global bindings per OS, merged the NbKeymap way: keystrokes -> {name, target}. */
    private static Map<Os, Map<String, List<String[]>>> defaultGlobals(Cluster cluster) {
        Map<String, String[]> byName = new LinkedHashMap<>();
        for (String folder : List.of("Shortcuts", "Keymaps/" + DEFAULT_PROFILE)) {
            cluster.visible(folder).forEach((n, f) -> {
                int dot = n.lastIndexOf('.');
                String bare = dot > 0 ? n.substring(0, dot) : n;
                if (n.endsWith(".removed")) {
                    byName.remove(bare.toUpperCase(Locale.ROOT));
                } else if (n.endsWith(".shadow")) {
                    byName.put(bare.toUpperCase(Locale.ROOT), new String[] {bare, f.original()});
                }
            });
        }
        Map<Os, Map<String, List<String[]>>> out = new EnumMap<>(Os.class);
        for (Os os : Os.values()) {
            Map<String, List<String[]>> m = new LinkedHashMap<>();
            for (String[] b : byName.values()) {
                List<String> seq = strokes(b[0], os);
                if (seq != null) {
                    m.computeIfAbsent(String.join(" ", seq), k -> new ArrayList<>()).add(b);
                }
            }
            out.put(os, m);
        }
        return out;
    }

    private static void checkRows(Cluster cluster, List<Row> rows) {
        Set<String> editorActions = new TreeSet<>();
        cluster.files.forEach((folder, names) -> {
            if (folder.startsWith("Editors/") && folder.endsWith("/Actions")) {
                names.keySet().forEach(n -> editorActions.add(n.replaceFirst("\\.instance$", "")));
            }
        });
        for (KeybindingFile f : cluster.keybindings) {
            if (!f.folder().contains("/Keybindings/" + PROFILE + "/")) {
                f.binds().forEach(b -> {
                    if (b.action() != null) {
                        editorActions.add(b.action());
                    }
                });
            }
        }
        for (Row r : rows) {
            if (!r.bound()) {
                continue;
            }
            if (r.scope() == Scope.GLOBAL && !cluster.exists(r.target())) {
                throw new IllegalStateException(r + ": no module in the cluster registers " + r.target());
            }
            if (r.scope() == Scope.EDITOR) {
                List<String> targets = new ArrayList<>(r.variants().values());
                targets.add(r.target());
                for (String t : targets) {
                    if (!editorActions.contains(t)) {
                        throw new IllegalStateException(r + ": no editor action is registered or bound as " + t);
                    }
                }
            }
        }
    }

    /** {@code NbKeymap} drops a two-stroke chord whose first stroke is already a binding of its own. */
    private static void checkPrefixes(Cluster cluster, Map<String, LayerFile> shadows, Set<String> removed) {
        Map<String, String> byName = new LinkedHashMap<>();
        cluster.visible("Shortcuts").keySet().forEach(n -> {
            if (n.endsWith(".shadow")) {
                byName.put(n.substring(0, n.length() - 7).toUpperCase(Locale.ROOT), n);
            }
        });
        removed.forEach(n -> byName.remove(n.substring(0, n.length() - ".removed".length()).toUpperCase(Locale.ROOT)));
        shadows.keySet().forEach(n -> byName.put(n.substring(0, n.length() - 7).toUpperCase(Locale.ROOT), n));
        for (Os os : Os.values()) {
            for (String a : byName.keySet()) {
                List<String> sa = strokes(a, os);
                if (sa == null) {
                    throw new IllegalStateException(byName.get(a) + " is not a keystroke the platform can read");
                }
                for (String b : byName.keySet()) {
                    List<String> sb = strokes(b, os);
                    if (sb != null && sa.size() < sb.size() && VsCodeChordTable.collide(sa, sb)) {
                        throw new IllegalStateException(byName.get(a) + " is bound on the first stroke of "
                                + byName.get(b) + " on " + os + ": NbKeymap would drop the chord");
                    }
                }
            }
        }
    }

    private static void writeEditors(StringBuilder sb, Map<String, List<String[]>> registered) {
        // the base folder first, then each language under its mime's own folders
        folderOpen(sb, 2, "Keybindings");
        profileFolder(sb, 3, registered.getOrDefault("", List.of()), true);
        folderClose(sb, 2);
        Map<String, Map<String, List<String[]>>> byType = new TreeMap<>();
        registered.forEach((mime, entries) -> {
            if (!mime.isEmpty()) {
                int slash = mime.indexOf('/');
                byType.computeIfAbsent(mime.substring(0, slash), k -> new TreeMap<>())
                        .put(mime.substring(slash + 1), entries);
            }
        });
        byType.forEach((type, subtypes) -> {
            folderOpen(sb, 2, type);
            subtypes.forEach((subtype, entries) -> {
                folderOpen(sb, 3, subtype);
                folderOpen(sb, 4, "Keybindings");
                profileFolder(sb, 5, entries, false);
                folderClose(sb, 4);
                folderClose(sb, 3);
            });
            folderClose(sb, 2);
        });
    }

    private static void profileFolder(StringBuilder sb, int depth, List<String[]> entries, boolean named) {
        folderOpen(sb, depth, PROFILE);
        if (named) {
            indent(sb, depth + 1).append("<attr name=\"SystemFileSystem.localizingBundle\" stringvalue=\"")
                    .append(NAMES_BUNDLE).append("\"/>\n");
        }
        folderOpen(sb, depth + 1, "Defaults");
        for (String[] e : entries) {
            indent(sb, depth + 2).append("<file name=\"").append(e[0]).append("\" url=\"").append(FILES_DIR).append('/')
                    .append(xml(e[1])).append("\">\n");
            indent(sb, depth + 3).append("<attr name=\"position\" intvalue=\"").append(e[2]).append("\"/>\n");
            if (!e[3].isEmpty()) {
                indent(sb, depth + 3).append("<attr name=\"nbeditor-settings-targetOS\" stringvalue=\"").append(e[3])
                        .append("\"/>\n");
            }
            indent(sb, depth + 2).append("</file>\n");
        }
        folderClose(sb, depth + 1);
        folderClose(sb, depth);
    }

    private static StringBuilder indent(StringBuilder sb, int depth) {
        return sb.append("    ".repeat(depth));
    }

    private static void folderOpen(StringBuilder sb, int depth, String name) {
        indent(sb, depth).append("<folder name=\"").append(xml(name)).append("\">\n");
    }

    private static void folderClose(StringBuilder sb, int depth) {
        indent(sb, depth).append("</folder>\n");
    }

    private static String keybindingFile(Map<List<String>, String> removed, Map<List<String>, String> bound, String what) {
        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        sb.append("<!DOCTYPE bindings PUBLIC \"-//NetBeans//DTD Editor KeyBindings settings 1.1//EN\"\n");
        sb.append("                          \"http://www.netbeans.org/dtds/EditorKeyBindings-1_1.dtd\">\n");
        sb.append("<!--\n");
        sb.append("    GENERATED by scripts/generate-vscode-keymap.sh - do not edit.\n");
        sb.append("    The VS Code keymap profile, ").append(what).append(".\n");
        sb.append("    The default profile's bindings with scripts/vscode-keymap/chords.txt laid over them;\n");
        sb.append("    every key is spelled with explicit modifiers (S Shift, C Ctrl, A Alt, M Cmd).\n");
        sb.append("-->\n");
        sb.append("<bindings>\n");
        new TreeSet<>(removed.keySet().stream().map(s -> spell(s, " ")).toList())
                .forEach(k -> sb.append("    <bind key=\"").append(xml(k)).append("\" remove=\"true\"/>\n"));
        Map<String, String> sorted = new TreeMap<>();
        bound.forEach((seq, action) -> sorted.put(action + "\u0000" + spell(seq, " "), spell(seq, " ")));
        sorted.forEach((k, key) -> sb.append("    <bind actionName=\"").append(xml(k.substring(0, k.indexOf('\u0000'))))
                .append("\" key=\"").append(xml(key)).append("\"/>\n"));
        sb.append("</bindings>\n");
        return sb.toString();
    }

    static String spell(List<String> seq, String between) {
        List<String> out = new ArrayList<>();
        seq.forEach(s -> out.add(VsCodeChordTable.spell(s)));
        return String.join(between, out);
    }

    private static String xml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }

    /**
     * {@code displaced.txt}: every default binding a VS Code chord took, and
     * whether its action still has a chord in this profile on that OS.
     */
    private static String report(List<String> lost, Map<String, Map<Os, Map<List<String>, String>>> editor,
            Map<String, LayerFile> shadows, Cluster cluster, Set<String> removed) {
        Set<String> removedNames = new TreeSet<>();
        removed.forEach(n -> removedNames.add(n.substring(0, n.length() - ".removed".length()).toUpperCase(Locale.ROOT)));
        Set<String> globalTargets = new TreeSet<>();
        shadows.values().forEach(f -> globalTargets.add(f.original()));
        cluster.visible("Shortcuts").forEach((n, f) -> {
            String bare = n.substring(0, Math.max(0, n.length() - 7));
            // a Shortcuts entry still fires unless it is removed or a profile shadow of its name replaces it
            if (n.endsWith(".shadow") && !removedNames.contains(bare.toUpperCase(Locale.ROOT)) && !hasName(shadows, bare)) {
                globalTargets.add(f.original());
            }
        });
        Set<String> lines = new TreeSet<>();
        for (String l : lost) {
            String[] f = l.split(" \\| ", -1);
            String left;
            if (f[4].startsWith("not inherited")) {
                left = "";
            } else if (f[0].startsWith("editor")) {
                String mime = f[0].length() > "editor".length() ? f[0].substring("editor ".length()) : "";
                Os os = Os.valueOf(f[1]);
                List<String> still = new ArrayList<>();
                for (String m : mime.isEmpty() ? List.of("") : List.of(mime, "")) {
                    editor.get(m).get(os).forEach((seq, action) -> {
                        if (action.equals(f[3])) {
                            still.add(spell(seq, " "));
                        }
                    });
                }
                left = still.isEmpty() ? " | NO CHORD LEFT" : " | still on " + String.join(", ", new TreeSet<>(still));
            } else {
                left = globalTargets.contains(f[3]) ? " | still bound" : " | NO CHORD LEFT";
            }
            lines.add(l + left);
        }
        StringBuilder sb = new StringBuilder();
        sb.append("# GENERATED by scripts/generate-vscode-keymap.sh - do not edit.\n");
        sb.append("# What the VS Code keymap profile took from the default profile: every default binding\n");
        sb.append("# whose keystroke a row of chords.txt claims, and whether its action still has a chord\n");
        sb.append("# in this profile on that OS.\n");
        sb.append("# where | OS | default chord | default action | the VS Code command that took it | what is left\n");
        lines.forEach(l -> sb.append(l).append('\n'));
        return sb.toString();
    }

    // ---- the committed files ----------------------------------------------

    /** The text between two markers of the ui layer, the markers' own lines included. */
    static String region(String layer, String begin, String end) {
        int b = layer.indexOf(begin);
        int e = layer.indexOf(end);
        if (b < 0 || e < b) {
            throw new IllegalStateException("the ui layer has no " + begin + " ... " + end + " region");
        }
        int lineStart = layer.lastIndexOf('\n', b) + 1;
        int lineEnd = layer.indexOf('\n', e);
        return layer.substring(lineStart, lineEnd < 0 ? layer.length() : lineEnd + 1);
    }

    /** What is on disk now, in the shape of an {@link Output}; line endings folded so a CRLF checkout compares equal. */
    static Output committed() throws IOException {
        String layer = read(UI_LAYER);
        Map<String, String> files = new TreeMap<>();
        Path dir = UI_RESOURCES.resolve(FILES_DIR);
        if (Files.isDirectory(dir)) {
            try (Stream<Path> s = Files.list(dir)) {
                for (Path p : s.filter(p -> p.getFileName().toString().endsWith(".xml")).sorted().toList()) {
                    files.put(p.getFileName().toString(), read(p));
                }
            }
        }
        return new Output(region(layer, GLOBAL_BEGIN, GLOBAL_END), region(layer, EDITORS_BEGIN, EDITORS_END), files,
                Files.exists(DISPLACED) ? read(DISPLACED) : "");
    }

    private static String read(Path p) throws IOException {
        return Files.readString(p, StandardCharsets.UTF_8).replace("\r\n", "\n");
    }

    /** Writes what was generated over what is committed; a keybinding file no longer generated is deleted. */
    static void write(Output out) throws IOException {
        String layer = read(UI_LAYER);
        layer = layer.replace(region(layer, GLOBAL_BEGIN, GLOBAL_END), out.globalRegion());
        layer = layer.replace(region(layer, EDITORS_BEGIN, EDITORS_END), out.editorsRegion());
        Files.writeString(UI_LAYER, layer, StandardCharsets.UTF_8);
        Path dir = UI_RESOURCES.resolve(FILES_DIR);
        Files.createDirectories(dir);
        try (Stream<Path> s = Files.list(dir)) {
            for (Path p : s.filter(p -> p.getFileName().toString().endsWith(".xml")).toList()) {
                if (!out.files().containsKey(p.getFileName().toString())) {
                    Files.delete(p);
                }
            }
        }
        for (Map.Entry<String, String> f : out.files().entrySet()) {
            Files.writeString(dir.resolve(f.getKey()), f.getValue(), StandardCharsets.UTF_8);
        }
        Files.writeString(DISPLACED, out.displaced(), StandardCharsets.UTF_8);
    }

    private VsCodeKeymapProfile() {
    }
}
