package org.nmox.studio.rack.projectstudio;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The A11y Kit (v2.38.0, David's ask: a11y support 100%) — the kit
 * family's accessibility member: makes a web project
 * accessible-by-default the way the Standards Kit makes it lawful.
 * Three artifacts, every kit law held (never-clobber, idempotent
 * wiring, honest refusals): an {@code a11y.css} starter carrying the
 * four highest-leverage rules (a visible {@code :focus-visible} ring,
 * the {@code .visually-hidden} utility, the skip-link reveal, and
 * {@code prefers-reduced-motion}), an {@code A11Y-NOTES.md} checklist
 * that points at the product's own tools (the DevTools contrast
 * verdict, the VITALS Lighthouse a11y gate) and says honestly what
 * automation cannot catch, and idempotent {@code index.html} wiring —
 * {@code lang} on the html tag, a skip link after {@code <body>}, the
 * stylesheet in {@code <head>} — plus a WARNING (never an edit) when
 * the viewport meta disables pinch zoom. Pure so every rule is a unit
 * test.
 */
public final class A11yKit {

    private A11yKit() {
    }

    public record Options(boolean stylesheet, boolean notes, boolean wireIndex) {
    }

    /** What happened, in the kits' shared vocabulary. */
    public record Outcome(String path, boolean written, String note) {

        public Outcome(String path, boolean written) {
            this(path, written, "");
        }
    }

    // ---- the stylesheet ---------------------------------------------------

    public static String stylesheet() {
        return """
            /* a11y.css — accessibility starter (NMOX A11y Kit)
               Four rules that carry most of the keyboard/AT experience.
               Own this file: it is yours now, the kit never rewrites it. */

            /* 1 · Keyboard focus is always visible — never remove this
                   without replacing it with something MORE visible. */
            :focus-visible {
              outline: 3px solid #4c9ffe;
              outline-offset: 2px;
            }

            /* 2 · Screen-reader-only text: visually hidden, still read. */
            .visually-hidden {
              position: absolute;
              width: 1px;
              height: 1px;
              padding: 0;
              margin: -1px;
              overflow: hidden;
              clip: rect(0 0 0 0);
              white-space: nowrap;
              border: 0;
            }

            /* 3 · The skip link: off-screen until a keyboard user needs it. */
            .skip-link {
              position: absolute;
              left: -999px;
              top: 0;
              background: #1a1a1e;
              color: #ffffff;
              padding: 0.5em 1em;
              z-index: 1000;
            }
            .skip-link:focus {
              left: 0;
            }

            /* 4 · Respect the motion preference: animation is a choice. */
            @media (prefers-reduced-motion: reduce) {
              *, *::before, *::after {
                animation-duration: 0.01ms !important;
                animation-iteration-count: 1 !important;
                transition-duration: 0.01ms !important;
                scroll-behavior: auto !important;
              }
            }
            """;
    }

    // ---- the notes --------------------------------------------------------

    public static String notes(String projectName) {
        return """
            # Accessibility notes — %s

            Generated by the NMOX A11y Kit. The kit wired the mechanical
            part; this checklist is the part only you can do. Honest
            framing first: automated checks catch roughly a third of
            accessibility problems. The rest is the keyboard walk and
            the questions below.

            ## The product's own tools

            - **Contrast**: open the page in the in-app Browser (⌥⌘4),
              DevTools ▸ DOM ▸ Pick element — the pane shows the WCAG
              contrast ratio with AA/AAA verdicts for normal and large
              text, computed from the element's real colors.
            - **The gate**: put VITALS on the rack and set GATE to
              accessibility — the Lighthouse a11y score becomes a floor
              your Run must clear, exportable to CI.

            ## The keyboard walk (do this once per screen)

            1. Unplug your mouse (really). Tab through the whole page.
            2. Can you SEE where focus is at every step? (a11y.css's
               `:focus-visible` ring is the floor, not the ceiling.)
            3. Can you reach and OPERATE every control — menus, dialogs,
               custom widgets? Escape closes what Enter opened?
            4. Does the skip link appear on first Tab and jump to main?

            ## The questions automation can't answer

            - Does every image's `alt` text say what the image MEANS
              here (empty `alt=""` for decoration is correct)?
            - Does every input have a real `<label for=…>` — placeholder
              text is not a label?
            - Do headings outline the page (one `h1`, no skipped levels)?
            - Landmarks: one `<main id="main">`, `<nav>`, `<header>`,
              `<footer>` — the skip link needs the `main` target.
            - Is anything conveyed by color alone?
            - Live regions: do async updates announce (`aria-live`)?

            ## Wired by the kit

            - `a11y.css` — focus ring, `.visually-hidden`, skip-link
              reveal, `prefers-reduced-motion`.
            - `index.html` — `lang` attribute, skip link after
              `<body>`, the stylesheet in `<head>` (idempotent: run the
              kit again and nothing doubles).
            """.formatted(projectName);
    }

    // ---- the wiring -------------------------------------------------------

    private static final Pattern HTML_TAG = Pattern.compile("<html\\b([^>]*)>",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern BODY_TAG = Pattern.compile("<body\\b[^>]*>",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern LANG_ATTR = Pattern.compile("\\blang\\s*=",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern ZOOM_DISABLED = Pattern.compile(
            "user-scalable\\s*=\\s*(no|0)|maximum-scale\\s*=\\s*1(\\.0*)?\\b",
            Pattern.CASE_INSENSITIVE);

    static final String SKIP_LINK =
            "\n  <a class=\"skip-link\" href=\"#main\">Skip to content</a>";
    static final String CSS_LINK =
            "  <link rel=\"stylesheet\" href=\"a11y.css\">\n";

    /**
     * Wires one page: {@code lang} on a lang-less html tag, the skip
     * link right after {@code <body>}, the stylesheet before
     * {@code </head>} — each edit presence-checked first, so the whole
     * method is idempotent. Returns the page unchanged when a
     * precondition is missing; the caller reports which.
     */
    static String wire(String html) {
        String out = html;
        Matcher tag = HTML_TAG.matcher(out);
        if (tag.find() && !LANG_ATTR.matcher(tag.group(1)).find()) {
            out = out.substring(0, tag.end(1)) + " lang=\"en\""
                    + out.substring(tag.end(1));
        }
        if (!out.contains("class=\"skip-link\"")) {
            Matcher body = BODY_TAG.matcher(out);
            if (body.find()) {
                out = out.substring(0, body.end()) + SKIP_LINK
                        + out.substring(body.end());
            }
        }
        if (!out.contains("a11y.css")) {
            out = HtmlWiring.insertBeforeHeadClose(out, CSS_LINK);
        }
        return out;
    }

    /** True when the page's viewport meta disables pinch zoom. */
    static boolean zoomDisabled(String html) {
        return ZOOM_DISABLED.matcher(html).find();
    }

    // ---- the write --------------------------------------------------------

    public static List<Outcome> write(File projectDir, Options opts) throws IOException {
        List<Outcome> outcomes = new ArrayList<>();
        if (opts.stylesheet()) {
            outcomes.add(writeOne(projectDir, "a11y.css", stylesheet()));
        }
        if (opts.notes()) {
            outcomes.add(writeOne(projectDir, "A11Y-NOTES.md",
                    notes(projectDir.getName())));
        }
        if (opts.wireIndex()) {
            outcomes.add(wireIndex(projectDir));
        }
        return outcomes;
    }

    private static Outcome wireIndex(File projectDir) throws IOException {
        File index = new File(projectDir, "index.html");
        if (!index.isFile()) {
            index = new File(projectDir, "public/index.html");
        }
        if (!index.isFile()) {
            return new Outcome("index.html", false,
                    "no index.html found — wire the skip link and a11y.css"
                    + " into your entry page by hand (A11Y-NOTES.md shows what goes where)");
        }
        String rel = index.getParentFile().equals(projectDir)
                ? "index.html" : "public/index.html";
        String before = Files.readString(index.toPath(), StandardCharsets.UTF_8);
        String after = wire(before);
        String zoomNote = zoomDisabled(before)
                ? " WARNING: the viewport meta disables pinch zoom"
                + " (user-scalable=no / maximum-scale=1) — low-vision users"
                + " need zoom; the kit never rewrites your markup, so remove"
                + " that yourself" : "";
        if (after.equals(before)) {
            return new Outcome(rel, false, ("already wired — the kit is"
                    + " idempotent." + zoomNote).strip());
        }
        Files.writeString(index.toPath(), after, StandardCharsets.UTF_8);
        return new Outcome(rel, true, ("lang + skip link + a11y.css wired;"
                + " give your main content id=\"main\" so the skip link lands."
                + zoomNote).strip());
    }

    private static Outcome writeOne(File dir, String relative, String content)
            throws IOException {
        File target = new File(dir, relative);
        if (target.exists()) {
            return new Outcome(relative, false, "already exists, untouched");
        }
        Files.createDirectories(target.getParentFile().toPath());
        Files.writeString(target.toPath(), content, StandardCharsets.UTF_8);
        return new Outcome(relative, true);
    }
}
