package org.nmox.studio.rack.projectstudio;

import java.io.File;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.nmox.studio.rack.devices.CommandDevice;
import org.nmox.studio.rack.devices.ProjectInspector;
import org.nmox.studio.rack.model.Cable;
import org.nmox.studio.rack.model.Rack;
import org.nmox.studio.rack.model.RackDevice;

/**
 * Compiles the rack patch into a GitHub Actions workflow: the same
 * pipeline you designed with cables, expressed as ordered steps with
 * the SAME resolved commands the devices would run locally. Design
 * visally, run locally, ship the identical pipeline to CI.
 */
public final class CiExporter {

    /** Device kinds that translate into CI steps. */
    private static final Set<String> STEP_KINDS = Set.of(
            "package-manager", "build", "test", "typecheck", "lint", "format",
            "npm-script", "run", "angular", "nextjs", "phoenix", "audit");

    private CiExporter() {
    }

    /** The workflow YAML for the rack's current design and knob state. */
    public static String toWorkflowYaml(Rack rack) {
        StringBuilder yaml = new StringBuilder();
        yaml.append("# Generated by NMOX Studio from the rack patch.\n");
        yaml.append("# The steps run the same commands the rack devices run locally.\n");
        yaml.append("name: NMOX Rack Pipeline\n\n");
        yaml.append("on:\n  push:\n    branches: [ main ]\n  pull_request:\n    branches: [ main ]\n\n");
        yaml.append("jobs:\n  rack:\n    runs-on: ubuntu-latest\n    steps:\n");
        yaml.append("      - uses: actions/checkout@v4\n");

        for (String setup : setupSteps(rack.getProjectDir())) {
            yaml.append(setup);
        }

        File root = rack.getProjectDir();
        for (RackDevice device : orderedStepDevices(rack)) {
            CommandDevice cd = (CommandDevice) device;
            List<String> command = cd.exportCommand();
            if (command == null || command.isEmpty()) {
                continue;
            }
            yaml.append("      - name: ").append(device.getTitle())
                    .append(" (").append(device.getTypeId()).append(")\n");
            String dir = relative(root, cd.exportDir());
            if (!dir.isEmpty()) {
                yaml.append("        working-directory: ").append(dir).append('\n');
            }
            yaml.append("        run: ").append(String.join(" ", command)).append('\n');
        }
        return yaml.toString();
    }

    /**
     * Step devices in cable order: Kahn's algorithm over trigger cables
     * between exportable devices, stable by rack position otherwise.
     */
    static List<RackDevice> orderedStepDevices(Rack rack) {
        List<RackDevice> candidates = new ArrayList<>();
        for (RackDevice d : rack.getDevices()) {
            if (d instanceof CommandDevice && STEP_KINDS.contains(d.getTypeId())) {
                candidates.add(d);
            }
        }
        Map<RackDevice, Integer> indegree = new LinkedHashMap<>();
        Map<RackDevice, List<RackDevice>> next = new LinkedHashMap<>();
        for (RackDevice d : candidates) {
            indegree.put(d, 0);
        }
        for (Cable cable : rack.getCables()) {
            RackDevice from = cable.getFrom().getDevice();
            RackDevice to = cable.getTo().getDevice();
            if (indegree.containsKey(from) && indegree.containsKey(to) && from != to) {
                indegree.merge(to, 1, Integer::sum);
                next.computeIfAbsent(from, k -> new ArrayList<>()).add(to);
            }
        }
        Deque<RackDevice> ready = new ArrayDeque<>();
        indegree.forEach((d, deg) -> {
            if (deg == 0) {
                ready.add(d);
            }
        });
        List<RackDevice> ordered = new ArrayList<>();
        Set<RackDevice> seen = new LinkedHashSet<>();
        while (!ready.isEmpty()) {
            RackDevice d = ready.poll();
            if (!seen.add(d)) {
                continue;
            }
            ordered.add(d);
            for (RackDevice n : next.getOrDefault(d, List.of())) {
                if (indegree.merge(n, -1, Integer::sum) == 0) {
                    ready.add(n);
                }
            }
        }
        // cycles or uncabled stragglers keep their rack order at the end
        for (RackDevice d : candidates) {
            if (!seen.contains(d)) {
                ordered.add(d);
            }
        }
        return ordered;
    }

    /** Toolchain setup actions for every kind the project carries. */
    static List<String> setupSteps(File projectDir) {
        List<String> steps = new ArrayList<>();
        var kinds = ProjectInspector.detectKinds(projectDir);
        for (var kind : kinds.keySet()) {
            switch (kind) {
                case NODE -> steps.add("""
                          - uses: actions/setup-node@v4
                            with: { node-version: 22 }
                    """.stripTrailing() + "\n");
                case RUST -> steps.add("      - uses: dtolnay/rust-toolchain@stable\n");
                case GO -> steps.add("""
                          - uses: actions/setup-go@v5
                            with: { go-version: stable }
                    """.stripTrailing() + "\n");
                case PYTHON -> steps.add("""
                          - uses: actions/setup-python@v5
                            with: { python-version: '3.12' }
                    """.stripTrailing() + "\n");
                case MAVEN, GRADLE -> steps.add("""
                          - uses: actions/setup-java@v4
                            with: { distribution: temurin, java-version: 17 }
                    """.stripTrailing() + "\n");
                case ELIXIR, ERLANG -> steps.add("""
                          - uses: erlef/setup-beam@v1
                            with: { otp-version: '27', elixir-version: '1.17' }
                    """.stripTrailing() + "\n");
                case RUBY -> steps.add("""
                          - uses: ruby/setup-ruby@v1
                            with: { ruby-version: '3.3', bundler-cache: true }
                    """.stripTrailing() + "\n");
                case PHP -> steps.add("""
                          - uses: shivammathur/setup-php@v2
                            with: { php-version: '8.3' }
                    """.stripTrailing() + "\n");
                default -> {
                    // make/cmake/swift ride on the runner image
                }
            }
        }
        return steps;
    }

    private static String relative(File root, File dir) {
        if (dir == null || dir.equals(root)) {
            return "";
        }
        String rel = root.toPath().relativize(dir.toPath()).toString();
        return rel.isEmpty() || rel.startsWith("..") ? "" : rel;
    }
}
