package org.nmox.studio.rack.projectstudio;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

/**
 * The I18n Kit (v2.37.5, David's ask: "all that for i18n, too") — the
 * kit family's internationalization member, the A11y Kit's sibling:
 * makes a web project translatable-by-default. Four artifacts, every
 * kit law held (never-clobber, idempotent wiring, honest refusals):
 * a {@code locales/} pair (a real English catalog plus a Spanish one
 * proving the shape holds two languages), a dependency-free
 * {@code i18n.js} that applies the catalog to {@code data-i18n}
 * markup and keeps {@code <html lang>} truthful, an
 * {@code I18N-NOTES.md} checklist that says honestly what tooling
 * cannot catch (concatenated fragments, hand-formatted dates, the RTL
 * walk), and idempotent {@code index.html} wiring for the script tag.
 * Pure so every rule is a unit test.
 */
public final class I18nKit {

    private I18nKit() {
    }

    public record Options(boolean locales, boolean helper, boolean notes,
            boolean wireIndex) {
    }

    /** What happened, in the kits' shared vocabulary. */
    public record Outcome(String path, boolean written, String note) {

        public Outcome(String path, boolean written) {
            this(path, written, "");
        }
    }

    // ---- the catalogs -----------------------------------------------------

    public static String enCatalog(String projectName) {
        return """
            {
              "app.title": %s,
              "app.greeting": "Hello!",
              "app.language": "Language"
            }
            """.formatted(org.json.JSONObject.quote(projectName));
    }

    public static String esCatalog(String projectName) {
        return """
            {
              "app.title": %s,
              "app.greeting": "¡Hola!",
              "app.language": "Idioma"
            }
            """.formatted(org.json.JSONObject.quote(projectName));
    }

    // ---- the helper -------------------------------------------------------

    public static String helper() {
        return """
            /* i18n.js — internationalization starter (NMOX I18n Kit)
               Dependency-free and readable: a catalog per locale in
               ./locales/<tag>.json, applied to every element carrying
               data-i18n="key". Own this file: the kit never rewrites it.

               Markup:   <h1 data-i18n="app.title"></h1>
               Switch:   setLocale('es')
               Add one:  copy locales/en.json, translate the values. */

            const I18N = {
              locale: 'en',
              messages: {},
            };

            async function setLocale(tag) {
              const res = await fetch(`locales/${tag}.json`);
              if (!res.ok) {
                console.warn(`i18n: no catalog for "${tag}", staying on "${I18N.locale}"`);
                return;
              }
              I18N.messages = await res.json();
              I18N.locale = tag;
              // keep the document's language claim TRUE — screen readers
              // pick pronunciation from it, and CSS/:lang() keys off it
              document.documentElement.lang = tag;
              applyTranslations();
            }

            function t(key) {
              // a missing key returns the key itself — visible in the UI,
              // never a silent blank
              return I18N.messages[key] ?? key;
            }

            function applyTranslations() {
              for (const el of document.querySelectorAll('[data-i18n]')) {
                el.textContent = t(el.getAttribute('data-i18n'));
              }
            }

            // first load: the visitor's language if a catalog exists,
            // English otherwise
            setLocale((navigator.language || 'en').split('-')[0]);
            """;
    }

    // ---- the notes --------------------------------------------------------

    public static String notes(String projectName) {
        return """
            # Internationalization notes — %s

            Generated by the NMOX I18n Kit. The kit wired the mechanical
            part; this checklist is the part only you can do.

            ## Wired by the kit

            - `locales/en.json` + `locales/es.json` — one catalog per
              language; the Spanish one proves the shape holds two.
            - `i18n.js` — applies the catalog to `data-i18n` markup,
              keeps `<html lang>` truthful, falls back to the key (never
              a silent blank), detects the visitor's language.
            - `index.html` — the script tag (idempotent: run the kit
              again and nothing doubles).

            ## Mark up your text

            Replace hardcoded copy with keys:

                <h1 data-i18n="app.title"></h1>

            and add the string to EVERY catalog in `locales/`. A key
            showing up literally on the page means a catalog is missing
            that entry — that visibility is deliberate.

            ## The rules tooling can't enforce

            - **Never concatenate translated fragments.** Word order
              differs by language; one key per full sentence, with
              placeholders if you need them.
            - **Dates, numbers, currencies: use `Intl`.**
              `new Intl.DateTimeFormat(I18N.locale).format(date)` and
              `Intl.NumberFormat` — never hand-assembled `mm/dd/yyyy`.
            - **Leave room.** German runs ~35%% longer than English;
              truncated buttons are the classic tell. Don't fix widths
              to the English string.
            - **The RTL walk.** Add an Arabic or Hebrew catalog someday?
              Set `document.documentElement.dir = 'rtl'` and walk every
              screen; prefer CSS logical properties
              (`margin-inline-start`) over left/right today so that day
              is cheap.
            - **Pseudo-localization.** Copy `en.json` to `locales/xa.json`
              and wrap every value in brackets with accents
              (`[Ĥéļļō!]`) — untranslated strings and clipped layouts
              jump out immediately.
            - **`lang` per element** for mixed-language content
              (`<span lang="fr">`) so screen readers switch voices.

            ## The product's own tools

            - The in-app Browser (⌥⌘4) + viewport presets: check the
              longest locale on the smallest screen.
            - `Copy TS Types` on a catalog JSON gives you an interface
              of your message keys for typo-proof lookups in TypeScript.
            """.formatted(projectName);
    }

    // ---- the wiring -------------------------------------------------------

    static final String SCRIPT_TAG = "  <script src=\"i18n.js\" defer></script>\n";

    /**
     * Wires one page: the script tag before {@code </head>},
     * presence-checked first so the method is idempotent. Returns the
     * page unchanged when there is no head to wire into; the caller
     * reports which.
     */
    static String wire(String html) {
        if (html.contains("i18n.js")) {
            return html;
        }
        return HtmlWiring.insertBeforeHeadClose(html, SCRIPT_TAG);
    }

    // ---- the write --------------------------------------------------------

    public static List<Outcome> write(File projectDir, Options opts) throws IOException {
        List<Outcome> outcomes = new ArrayList<>();
        String name = projectDir.getName();
        if (opts.locales()) {
            outcomes.add(writeOne(projectDir, "locales/en.json", enCatalog(name)));
            outcomes.add(writeOne(projectDir, "locales/es.json", esCatalog(name)));
        }
        if (opts.helper()) {
            outcomes.add(writeOne(projectDir, "i18n.js", helper()));
        }
        if (opts.notes()) {
            outcomes.add(writeOne(projectDir, "I18N-NOTES.md", notes(name)));
        }
        if (opts.wireIndex()) {
            outcomes.add(wireIndex(projectDir));
        }
        return outcomes;
    }

    private static Outcome wireIndex(File projectDir) throws IOException {
        File index = KitFiles.entryPage(projectDir);
        if (index == null) {
            return new Outcome("index.html", false,
                    "no index.html found — add the i18n.js script tag to your"
                    + " entry page by hand (I18N-NOTES.md shows what goes where)");
        }
        String rel = KitFiles.entryPageRel(projectDir, index);
        String before = Files.readString(index.toPath(), StandardCharsets.UTF_8);
        String after = wire(before);
        if (after.equals(before)) {
            return new Outcome(rel, false, before.contains("i18n.js")
                    ? "already wired — the kit is idempotent."
                    : "no </head> to wire into — add the script tag by hand");
        }
        Files.writeString(index.toPath(), after, StandardCharsets.UTF_8);
        return new Outcome(rel, true,
                "i18n.js wired; mark your text with data-i18n keys next"
                + " (I18N-NOTES.md walks it).");
    }

    private static Outcome writeOne(File dir, String relative, String content)
            throws IOException {
        File target = new File(dir, relative);
        if (target.exists()) {
            return new Outcome(relative, false, "already exists, untouched");
        }
        Files.createDirectories(target.getParentFile().toPath());
        Files.writeString(target.toPath(), content, StandardCharsets.UTF_8);
        return new Outcome(relative, true);
    }
}
