package org.nmox.studio.rack.projectstudio;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import org.json.JSONObject;
import org.nmox.studio.rack.devices.DeviceType;
import org.nmox.studio.rack.model.Rack;
import org.nmox.studio.rack.model.RackDevice;
import org.nmox.studio.rack.model.RackIO;

import static org.nmox.studio.rack.projectstudio.RackPresets.add;
import static org.nmox.studio.rack.projectstudio.RackPresets.buildPatchFrom;

/**
 * Project starters. Each template generates a complete, working
 * project offline - real source files, a package.json with the right
 * scripts and dependencies - plus a .nmoxrack.json with the infra for
 * that stack already wired: create a Vite project and the rack comes
 * up with SURGE on 5173 patched into the browser, FORGE on vite,
 * VERITAS on vitest, and a REFLEX TDD loop one switch away.
 */
public enum ProjectTemplates {

    VANILLA("Vanilla Web", "HTML/CSS/JS, no build step, static dev server") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "scripts": {
                    "dev": "http-server -p 8080 -c-1 .",
                    "start": "http-server -p 8080 ."
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "http-server": "^14.1.1",
                    "prettier": "^3.3.3"
                  }
                }
                """.formatted(name));
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                    <link rel="stylesheet" href="style.css" />
                  </head>
                  <body>
                    <main>
                      <h1>%s</h1>
                      <p>Generated by NMOX Studio. Edit <code>main.js</code> and save.</p>
                      <button id="counter">clicks: 0</button>
                    </main>
                    <script type="module" src="main.js"></script>
                  </body>
                </html>
                """.formatted(name, name));
            write(dir, "style.css", """
                :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
                main { max-width: 40rem; margin: 4rem auto; padding: 0 1rem; }
                button { font: inherit; padding: 0.5rem 1rem; cursor: pointer; }
                """);
            write(dir, "main.js", """
                let clicks = 0;
                const button = document.querySelector('#counter');
                button.addEventListener('click', () => {
                  clicks += 1;
                  button.textContent = `clicks: ${clicks}`;
                });
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                // SURGE on http-server:8080 pops the browser when up
                RackDevice server = add(rack, DeviceType.DEV_SERVER,
                        Map.of("server", "2", "port", "4"));
                RackDevice browser = add(rack, DeviceType.BROWSER,
                        Map.of("url", "http://localhost:8080"));
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                rack.connect(server.getPort("url"), browser.getPort("url"));
                rack.connect(server.getPort("ready"), browser.getPort("open"));
                rack.connect(server.getPort("out"), console.getPort("in"));
            });
        }
    },

    VITE_REACT("Vite + React", "React 18 with Vite dev server and Vitest") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                    "test": "vitest run"
                  },
                  "dependencies": {
                    "react": "^18.3.1",
                    "react-dom": "^18.3.1"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "@vitejs/plugin-react": "^4.3.1",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "prettier": "^3.3.3",
                    "vite": "^5.4.0",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "vite.config.js", """
                import { defineConfig } from 'vite';
                import react from '@vitejs/plugin-react';

                export default defineConfig({
                  plugins: [react()],
                  server: { port: 5173 },
                });
                """);
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                  </head>
                  <body>
                    <div id="root"></div>
                    <script type="module" src="/src/main.jsx"></script>
                  </body>
                </html>
                """.formatted(name));
            write(dir, "src/main.jsx", """
                import React from 'react';
                import { createRoot } from 'react-dom/client';
                import App from './App.jsx';

                createRoot(document.getElementById('root')).render(
                  <React.StrictMode>
                    <App />
                  </React.StrictMode>,
                );
                """);
            write(dir, "src/App.jsx", """
                import { useState } from 'react';

                export default function App() {
                  const [clicks, setClicks] = useState(0);
                  return (
                    <main style={{ maxWidth: '40rem', margin: '4rem auto', fontFamily: 'system-ui' }}>
                      <h1>%s</h1>
                      <p>Generated by NMOX Studio. Edit <code>src/App.jsx</code> and save.</p>
                      <button onClick={() => setClicks(clicks + 1)}>clicks: {clicks}</button>
                    </main>
                  );
                }
                """.formatted(name));
            write(dir, "src/App.test.js", """
                import { describe, expect, it } from 'vitest';

                describe('%s', () => {
                  it('is wired up', () => {
                    expect(1 + 1).toBe(2);
                  });
                });
                """.formatted(name));
        }

        @Override
        JSONObject buildPatch() {
            return vitePatch();
        }
    },

    VITE_VUE("Vite + Vue", "Vue 3 with Vite dev server and Vitest") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                    "test": "vitest run"
                  },
                  "dependencies": {
                    "vue": "^3.4.35"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "@vitejs/plugin-vue": "^5.1.2",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "prettier": "^3.3.3",
                    "vite": "^5.4.0",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "vite.config.js", """
                import { defineConfig } from 'vite';
                import vue from '@vitejs/plugin-vue';

                export default defineConfig({
                  plugins: [vue()],
                  server: { port: 5173 },
                });
                """);
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                  </head>
                  <body>
                    <div id="app"></div>
                    <script type="module" src="/src/main.js"></script>
                  </body>
                </html>
                """.formatted(name));
            write(dir, "src/main.js", """
                import { createApp } from 'vue';
                import App from './App.vue';

                createApp(App).mount('#app');
                """);
            write(dir, "src/App.vue", """
                <script setup>
                import { ref } from 'vue';
                const clicks = ref(0);
                </script>

                <template>
                  <main style="max-width: 40rem; margin: 4rem auto; font-family: system-ui">
                    <h1>%s</h1>
                    <p>Generated by NMOX Studio. Edit <code>src/App.vue</code> and save.</p>
                    <button @click="clicks++">clicks: {{ clicks }}</button>
                  </main>
                </template>
                """.formatted(name));
            write(dir, "src/App.test.js", """
                import { describe, expect, it } from 'vitest';

                describe('%s', () => {
                  it('is wired up', () => {
                    expect(1 + 1).toBe(2);
                  });
                });
                """.formatted(name));
        }

        @Override
        JSONObject buildPatch() {
            return vitePatch();
        }
    },

    EXPRESS_API("Express API", "Node HTTP API with nodemon reload and node:test") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "nodemon server.js",
                    "start": "node server.js",
                    "test": "node --test"
                  },
                  "dependencies": {
                    "express": "^4.19.2"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "nodemon": "^3.1.4",
                    "prettier": "^3.3.3"
                  }
                }
                """.formatted(name));
            write(dir, "server.js", """
                import express from 'express';

                const app = express();
                const port = process.env.PORT ?? 3000;

                app.use(express.json());

                app.get('/', (req, res) => {
                  res.json({ name: '%s', status: 'ok' });
                });

                app.get('/health', (req, res) => {
                  res.json({ up: true, time: new Date().toISOString() });
                });

                app.listen(port, () => {
                  console.log(`%s listening on http://localhost:${port}`);
                });
                """.formatted(name, name));
            write(dir, "test/health.test.js", """
                import { test } from 'node:test';
                import assert from 'node:assert/strict';

                test('math still works', () => {
                  assert.equal(1 + 1, 2);
                });
                """);
            write(dir, ".env.example", """
                PORT=3000
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
                // npm run dev (nodemon) on port 3000; PING smoke-tests /health
                RackDevice server = add(rack, DeviceType.DEV_SERVER,
                        Map.of("server", "0", "port", "0"));
                RackDevice ping = add(rack, DeviceType.HTTP,
                        Map.of("url", "http://localhost:3000/health", "method", "0"));
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                rack.connect(server.getPort("ready"), ping.getPort("send"));
                rack.connect(ping.getPort("body"), console.getPort("in"));
                rack.connect(server.getPort("out"), console.getPort("in"));
                rack.connect(deps.getPort("out"), console.getPort("in"));
            });
        }
    },

    VITE_SVELTE("Vite + Svelte", "Svelte 4 with Vite dev server and Vitest") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                    "test": "vitest run"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "@sveltejs/vite-plugin-svelte": "^3.1.1",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "prettier": "^3.3.3",
                    "svelte": "^4.2.18",
                    "vite": "^5.4.0",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "vite.config.js", """
                import { defineConfig } from 'vite';
                import { svelte } from '@sveltejs/vite-plugin-svelte';

                export default defineConfig({
                  plugins: [svelte()],
                  server: { port: 5173 },
                });
                """);
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                  </head>
                  <body>
                    <div id="app"></div>
                    <script type="module" src="/src/main.js"></script>
                  </body>
                </html>
                """.formatted(name));
            write(dir, "src/main.js", """
                import App from './App.svelte';

                const app = new App({ target: document.getElementById('app') });

                export default app;
                """);
            write(dir, "src/App.svelte", """
                <script>
                  let clicks = 0;
                </script>

                <main style="max-width: 40rem; margin: 4rem auto; font-family: system-ui">
                  <h1>%s</h1>
                  <p>Generated by NMOX Studio. Edit <code>src/App.svelte</code> and save.</p>
                  <button on:click={() => (clicks += 1)}>clicks: {clicks}</button>
                </main>
                """.formatted(name));
            write(dir, "src/App.test.js", """
                import { describe, expect, it } from 'vitest';

                describe('%s', () => {
                  it('is wired up', () => {
                    expect(1 + 1).toBe(2);
                  });
                });
                """.formatted(name));
        }

        @Override
        JSONObject buildPatch() {
            return vitePatch();
        }
    },

    TS_LIBRARY("TypeScript Library", "tsc build, Vitest, ready to publish") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "type": "module",
                  "main": "dist/index.js",
                  "types": "dist/index.d.ts",
                  "files": ["dist"],
                  "scripts": {
                    "build": "tsc",
                    "test": "vitest run",
                    "prepublishOnly": "npm run build && npm test"
                  },
                  "devDependencies": {
                    "prettier": "^3.3.3",
                    "typescript": "^5.5.4",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "tsconfig.json", """
                {
                  "compilerOptions": {
                    "target": "ES2022",
                    "module": "NodeNext",
                    "moduleResolution": "NodeNext",
                    "declaration": true,
                    "outDir": "dist",
                    "strict": true,
                    "skipLibCheck": true
                  },
                  "include": ["src"]
                }
                """);
            write(dir, "src/index.ts", """
                /** Generated by NMOX Studio. */
                export function greet(who: string): string {
                  return `Hello, ${who}!`;
                }
                """);
            write(dir, "src/index.test.ts", """
                import { describe, expect, it } from 'vitest';
                import { greet } from './index.js';

                describe('greet', () => {
                  it('greets by name', () => {
                    expect(greet('rack')).toBe('Hello, rack!');
                  });
                });
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
                RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
                RackDevice typecheck = add(rack, DeviceType.TYPECHECK, null);
                RackDevice build = add(rack, DeviceType.BUILD, null);
                RackDevice test = add(rack, DeviceType.TEST, Map.of("framework", "2"));
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                // save -> typecheck -> tests; CI: install -> build -> tests
                rack.connect(reflex.getPort("changed"), typecheck.getPort("run"));
                rack.connect(typecheck.getPort("ok"), test.getPort("run"));
                rack.connect(deps.getPort("ok"), build.getPort("run"));
                rack.connect(build.getPort("ok"), test.getPort("run"));
                rack.connect(test.getPort("out"), console.getPort("in"));
                rack.connect(typecheck.getPort("out"), console.getPort("in"));
            });
        }

        @Override
        boolean lintable() {
            return false; // eslint flat config can't parse TS without typescript-eslint
        }
    };

    private final String displayName;
    private final String description;

    ProjectTemplates(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getDescription() {
        return description;
    }

    abstract void writeFiles(Path dir, String name) throws IOException;

    abstract JSONObject buildPatch();

    /** Whether the generated project gets an eslint flat config. */
    boolean lintable() {
        return true;
    }

    /**
     * Generates the project into {@code dir} (created; must not already
     * contain files): sources, package.json, .gitignore, README, and the
     * pre-wired rack patch.
     */
    public void generate(File dir, String name) throws IOException {
        Path root = dir.toPath();
        Files.createDirectories(root);
        try (var entries = Files.list(root)) {
            if (entries.findAny().isPresent()) {
                throw new IOException("Directory is not empty: " + dir);
            }
        }
        writeFiles(root, name);
        write(root, ".gitignore", """
            node_modules/
            dist/
            coverage/
            .env
            """);
        write(root, ".editorconfig", """
            root = true

            [*]
            charset = utf-8
            end_of_line = lf
            insert_final_newline = true
            indent_style = space
            indent_size = 2
            trim_trailing_whitespace = true
            """);
        write(root, ".prettierrc", """
            {
              "singleQuote": true,
              "semi": true,
              "printWidth": 100
            }
            """);
        if (lintable()) {
            write(root, "eslint.config.mjs", """
                import js from '@eslint/js';
                import globals from 'globals';

                export default [
                  js.configs.recommended,
                  {
                    languageOptions: {
                      globals: { ...globals.browser, ...globals.node },
                    },
                  },
                  { ignores: ['dist/', 'node_modules/', 'coverage/'] },
                ];
                """);
        }
        write(root, "README.md", """
            # %s

            Created with NMOX Studio (%s template).

            The Task Rack infra for this project lives in `.nmoxrack.json`
            and mounts automatically when the rack aims here:

            - press INSTALL on CRATE (or run `npm install`) once
            - START on SURGE serves the project and opens the browser
            - arm REFLEX's WATCH switch for a save-driven test loop
            """.formatted(name, displayName));
        Files.writeString(root.resolve(RackIO.DEFAULT_FILENAME),
                buildPatch().toString(2), StandardCharsets.UTF_8);
    }

    static void write(Path root, String relative, String content) throws IOException {
        Path target = root.resolve(relative);
        Files.createDirectories(target.getParent());
        Files.writeString(target, content, StandardCharsets.UTF_8);
    }

    /** Shared patch for the Vite-based templates (React/Vue). */
    private static JSONObject vitePatch() {
        return buildPatchFrom(rack -> {
            RackDevice master = add(rack, DeviceType.MASTER, null);
            RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
            RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
            // vite on 5173
            RackDevice server = add(rack, DeviceType.DEV_SERVER, Map.of("server", "1", "port", "2"));
            RackDevice browser = add(rack, DeviceType.BROWSER, Map.of("url", "http://localhost:5173"));
            RackDevice build = add(rack, DeviceType.BUILD, Map.of("tool", "1"));
            RackDevice test = add(rack, DeviceType.TEST, Map.of("framework", "2"));
            RackDevice console = add(rack, DeviceType.CONSOLE, null);

            // CI lane
            rack.connect(master.getPort("trig1"), deps.getPort("run"));
            rack.connect(deps.getPort("ok"), build.getPort("run"));
            rack.connect(build.getPort("ok"), test.getPort("run"));
            rack.connect(test.getPort("out"), console.getPort("in"));
            // dev lane
            rack.connect(server.getPort("url"), browser.getPort("url"));
            rack.connect(server.getPort("ready"), browser.getPort("open"));
            // TDD lane (arm REFLEX to activate)
            rack.connect(reflex.getPort("changed"), test.getPort("run"));
        });
    }
}
