package org.nmox.studio.rack.projectstudio;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import org.json.JSONObject;
import org.nmox.studio.rack.devices.DeviceType;
import org.nmox.studio.rack.model.Rack;
import org.nmox.studio.rack.model.RackDevice;
import org.nmox.studio.rack.model.RackIO;

import static org.nmox.studio.rack.projectstudio.RackPresets.add;
import static org.nmox.studio.rack.projectstudio.RackPresets.buildPatchFrom;

/**
 * Project starters. Each template generates a complete, working
 * project offline - real source files, a package.json with the right
 * scripts and dependencies - plus a .nmoxrack.json with the infra for
 * that stack already wired: create a Vite project and the rack comes
 * up with SURGE on 5173 patched into the browser, FORGE on vite,
 * VERITAS on vitest, and a REFLEX TDD loop one switch away.
 */
public enum ProjectTemplates {

    VANILLA("Vanilla Web", "HTML/CSS/JS, no build step, static dev server") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "scripts": {
                    "dev": "http-server -p 8080 -c-1 .",
                    "start": "http-server -p 8080 ."
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "http-server": "^14.1.1",
                    "prettier": "^3.3.3"
                  }
                }
                """.formatted(name));
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                    <link rel="stylesheet" href="style.css" />
                  </head>
                  <body>
                    <main>
                      <h1>%s</h1>
                      <p>Generated by NMOX Studio. Edit <code>main.js</code> and save.</p>
                      <button id="counter">clicks: 0</button>
                    </main>
                    <script type="module" src="main.js"></script>
                  </body>
                </html>
                """.formatted(name, name));
            write(dir, "style.css", """
                :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
                main { max-width: 40rem; margin: 4rem auto; padding: 0 1rem; }
                button { font: inherit; padding: 0.5rem 1rem; cursor: pointer; }
                """);
            write(dir, "main.js", """
                let clicks = 0;
                const button = document.querySelector('#counter');
                button.addEventListener('click', () => {
                  clicks += 1;
                  button.textContent = `clicks: ${clicks}`;
                });
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                // SURGE on http-server:8080 pops the browser when up
                RackDevice server = add(rack, DeviceType.DEV_SERVER,
                        Map.of("server", "2", "port", "4"));
                RackDevice browser = add(rack, DeviceType.BROWSER,
                        Map.of("url", "http://localhost:8080"));
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                rack.connect(server.getPort("url"), browser.getPort("url"));
                rack.connect(server.getPort("ready"), browser.getPort("open"));
                rack.connect(server.getPort("out"), console.getPort("in"));
            });
        }
    },

    VITE_REACT("Vite + React", "React 18 with Vite dev server and Vitest") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                    "test": "vitest run"
                  },
                  "dependencies": {
                    "react": "^18.3.1",
                    "react-dom": "^18.3.1"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "@vitejs/plugin-react": "^4.3.1",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "prettier": "^3.3.3",
                    "vite": "^5.4.0",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "vite.config.js", """
                import { defineConfig } from 'vite';
                import react from '@vitejs/plugin-react';

                export default defineConfig({
                  plugins: [react()],
                  server: { port: 5173 },
                });
                """);
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                  </head>
                  <body>
                    <div id="root"></div>
                    <script type="module" src="/src/main.jsx"></script>
                  </body>
                </html>
                """.formatted(name));
            write(dir, "src/main.jsx", """
                import React from 'react';
                import { createRoot } from 'react-dom/client';
                import App from './App.jsx';

                createRoot(document.getElementById('root')).render(
                  <React.StrictMode>
                    <App />
                  </React.StrictMode>,
                );
                """);
            write(dir, "src/App.jsx", """
                import { useState } from 'react';

                export default function App() {
                  const [clicks, setClicks] = useState(0);
                  return (
                    <main style={{ maxWidth: '40rem', margin: '4rem auto', fontFamily: 'system-ui' }}>
                      <h1>%s</h1>
                      <p>Generated by NMOX Studio. Edit <code>src/App.jsx</code> and save.</p>
                      <button onClick={() => setClicks(clicks + 1)}>clicks: {clicks}</button>
                    </main>
                  );
                }
                """.formatted(name));
            write(dir, "src/App.test.js", """
                import { describe, expect, it } from 'vitest';

                describe('%s', () => {
                  it('is wired up', () => {
                    expect(1 + 1).toBe(2);
                  });
                });
                """.formatted(name));
        }

        @Override
        JSONObject buildPatch() {
            return vitePatch();
        }
    },

    VITE_VUE("Vite + Vue", "Vue 3 with Vite dev server and Vitest") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                    "test": "vitest run"
                  },
                  "dependencies": {
                    "vue": "^3.4.35"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "@vitejs/plugin-vue": "^5.1.2",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "prettier": "^3.3.3",
                    "vite": "^5.4.0",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "vite.config.js", """
                import { defineConfig } from 'vite';
                import vue from '@vitejs/plugin-vue';

                export default defineConfig({
                  plugins: [vue()],
                  server: { port: 5173 },
                });
                """);
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                  </head>
                  <body>
                    <div id="app"></div>
                    <script type="module" src="/src/main.js"></script>
                  </body>
                </html>
                """.formatted(name));
            write(dir, "src/main.js", """
                import { createApp } from 'vue';
                import App from './App.vue';

                createApp(App).mount('#app');
                """);
            write(dir, "src/App.vue", """
                <script setup>
                import { ref } from 'vue';
                const clicks = ref(0);
                </script>

                <template>
                  <main style="max-width: 40rem; margin: 4rem auto; font-family: system-ui">
                    <h1>%s</h1>
                    <p>Generated by NMOX Studio. Edit <code>src/App.vue</code> and save.</p>
                    <button @click="clicks++">clicks: {{ clicks }}</button>
                  </main>
                </template>
                """.formatted(name));
            write(dir, "src/App.test.js", """
                import { describe, expect, it } from 'vitest';

                describe('%s', () => {
                  it('is wired up', () => {
                    expect(1 + 1).toBe(2);
                  });
                });
                """.formatted(name));
        }

        @Override
        JSONObject buildPatch() {
            return vitePatch();
        }
    },

    EXPRESS_API("Express API", "Node HTTP API with nodemon reload and node:test") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "nodemon server.js",
                    "start": "node server.js",
                    "test": "node --test"
                  },
                  "dependencies": {
                    "express": "^4.19.2"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "nodemon": "^3.1.4",
                    "prettier": "^3.3.3"
                  }
                }
                """.formatted(name));
            write(dir, "server.js", """
                import express from 'express';

                const app = express();
                const port = process.env.PORT ?? 3000;

                app.use(express.json());

                app.get('/', (req, res) => {
                  res.json({ name: '%s', status: 'ok' });
                });

                app.get('/health', (req, res) => {
                  res.json({ up: true, time: new Date().toISOString() });
                });

                app.listen(port, () => {
                  console.log(`%s listening on http://localhost:${port}`);
                });
                """.formatted(name, name));
            write(dir, "test/health.test.js", """
                import { test } from 'node:test';
                import assert from 'node:assert/strict';

                test('math still works', () => {
                  assert.equal(1 + 1, 2);
                });
                """);
            write(dir, ".env.example", """
                PORT=3000
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
                // npm run dev (nodemon) on port 3000; PING smoke-tests /health
                RackDevice server = add(rack, DeviceType.DEV_SERVER,
                        Map.of("server", "0", "port", "0"));
                RackDevice ping = add(rack, DeviceType.HTTP,
                        Map.of("url", "http://localhost:3000/health", "method", "0"));
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                rack.connect(server.getPort("ready"), ping.getPort("send"));
                rack.connect(ping.getPort("body"), console.getPort("in"));
                rack.connect(server.getPort("out"), console.getPort("in"));
                rack.connect(deps.getPort("out"), console.getPort("in"));
            });
        }
    },

    VITE_SVELTE("Vite + Svelte", "Svelte 4 with Vite dev server and Vitest") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "type": "module",
                  "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                    "preview": "vite preview",
                    "test": "vitest run"
                  },
                  "devDependencies": {
                    "@eslint/js": "^9.9.0",
                    "@sveltejs/vite-plugin-svelte": "^3.1.1",
                    "eslint": "^9.9.0",
                    "globals": "^15.9.0",
                    "prettier": "^3.3.3",
                    "svelte": "^4.2.18",
                    "vite": "^5.4.0",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "vite.config.js", """
                import { defineConfig } from 'vite';
                import { svelte } from '@sveltejs/vite-plugin-svelte';

                export default defineConfig({
                  plugins: [svelte()],
                  server: { port: 5173 },
                });
                """);
            write(dir, "index.html", """
                <!doctype html>
                <html lang="en">
                  <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>%s</title>
                  </head>
                  <body>
                    <div id="app"></div>
                    <script type="module" src="/src/main.js"></script>
                  </body>
                </html>
                """.formatted(name));
            write(dir, "src/main.js", """
                import App from './App.svelte';

                const app = new App({ target: document.getElementById('app') });

                export default app;
                """);
            write(dir, "src/App.svelte", """
                <script>
                  let clicks = 0;
                </script>

                <main style="max-width: 40rem; margin: 4rem auto; font-family: system-ui">
                  <h1>%s</h1>
                  <p>Generated by NMOX Studio. Edit <code>src/App.svelte</code> and save.</p>
                  <button on:click={() => (clicks += 1)}>clicks: {clicks}</button>
                </main>
                """.formatted(name));
            write(dir, "src/App.test.js", """
                import { describe, expect, it } from 'vitest';

                describe('%s', () => {
                  it('is wired up', () => {
                    expect(1 + 1).toBe(2);
                  });
                });
                """.formatted(name));
        }

        @Override
        JSONObject buildPatch() {
            return vitePatch();
        }
    },

    TS_LIBRARY("TypeScript Library", "tsc build, Vitest, ready to publish") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "type": "module",
                  "main": "dist/index.js",
                  "types": "dist/index.d.ts",
                  "files": ["dist"],
                  "scripts": {
                    "build": "tsc",
                    "test": "vitest run",
                    "prepublishOnly": "npm run build && npm test"
                  },
                  "devDependencies": {
                    "prettier": "^3.3.3",
                    "typescript": "^5.5.4",
                    "vitest": "^2.0.5"
                  }
                }
                """.formatted(name));
            write(dir, "tsconfig.json", """
                {
                  "compilerOptions": {
                    "target": "ES2022",
                    "module": "NodeNext",
                    "moduleResolution": "NodeNext",
                    "declaration": true,
                    "outDir": "dist",
                    "strict": true,
                    "skipLibCheck": true
                  },
                  "include": ["src"]
                }
                """);
            write(dir, "src/index.ts", """
                /** Generated by NMOX Studio. */
                export function greet(who: string): string {
                  return `Hello, ${who}!`;
                }
                """);
            write(dir, "src/index.test.ts", """
                import { describe, expect, it } from 'vitest';
                import { greet } from './index.js';

                describe('greet', () => {
                  it('greets by name', () => {
                    expect(greet('rack')).toBe('Hello, rack!');
                  });
                });
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
                RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
                RackDevice typecheck = add(rack, DeviceType.TYPECHECK, null);
                RackDevice build = add(rack, DeviceType.BUILD, null);
                RackDevice test = add(rack, DeviceType.TEST, Map.of("framework", "2"));
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                // save -> typecheck -> tests; CI: install -> build -> tests
                rack.connect(reflex.getPort("changed"), typecheck.getPort("run"));
                rack.connect(typecheck.getPort("ok"), test.getPort("run"));
                rack.connect(deps.getPort("ok"), build.getPort("run"));
                rack.connect(build.getPort("ok"), test.getPort("run"));
                rack.connect(test.getPort("out"), console.getPort("in"));
                rack.connect(typecheck.getPort("out"), console.getPort("in"));
            });
        }

        @Override
        boolean lintable() {
            return false; // eslint flat config can't parse TS without typescript-eslint
        }
    },

    PYTHON_CLI("Python CLI", "pyproject + pytest, IGNITION-ready") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "pyproject.toml", """
                [project]
                name = "%s"
                version = "0.1.0"
                requires-python = ">=3.10"

                [tool.pytest.ini_options]
                testpaths = ["tests"]
                """.formatted(name));
            write(dir, "main.py", """
                def greet(name: str) -> str:
                    return f"Hello, {name}!"


                if __name__ == "__main__":
                    print(greet("NMOX"))
                """);
            write(dir, "tests/test_main.py", """
                from main import greet


                def test_greet():
                    assert greet("rack") == "Hello, rack!"
                """);
        }

        @Override
        JSONObject buildPatch() {
            return polyglotPatch();
        }

        @Override
        boolean lintable() {
            return false;
        }

        @Override
        boolean prettier() {
            return false;
        }

        @Override
        String gitignore() {
            return """
                __pycache__/
                *.pyc
                .venv/
                .pytest_cache/
                dist/
                """;
        }

        @Override
        String readmeHints() {
            return """
                - IGNITE on IGNITION runs main.py; VERITAS runs pytest
                - arm REFLEX's WATCH switch for a save-driven test loop
                - INSPECTOR launches debugpy on :5678 for your debugger
                """;
        }
    },

    GO_SERVICE("Go Service", "go.mod + net/http hello service, go test") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "go.mod", """
                module %s

                go 1.22
                """.formatted(name.toLowerCase().replaceAll("[^a-z0-9]", "")));
            write(dir, "main.go", """
                package main

                import (
                	"fmt"
                	"net/http"
                )

                func Greeting(name string) string {
                	return "Hello, " + name + "!"
                }

                func main() {
                	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                		fmt.Fprintln(w, Greeting("NMOX"))
                	})
                	fmt.Println("listening on http://localhost:8080")
                	http.ListenAndServe(":8080", nil)
                }
                """);
            write(dir, "main_test.go", """
                package main

                import "testing"

                func TestGreeting(t *testing.T) {
                	if Greeting("rack") != "Hello, rack!" {
                		t.Fatal("unexpected greeting")
                	}
                }
                """);
        }

        @Override
        JSONObject buildPatch() {
            return polyglotPatch();
        }

        @Override
        boolean lintable() {
            return false;
        }

        @Override
        boolean prettier() {
            return false;
        }

        @Override
        String gitignore() {
            return """
                bin/
                *.test
                """;
        }

        @Override
        String readmeHints() {
            return """
                - IGNITE on IGNITION runs `go run .` (listens on :8080)
                - VERITAS runs `go test ./...`; FORGE runs `go build ./...`
                - INSPECTOR launches delve headless on :2345
                """;
        }
    },

    RUST_CLI("Rust CLI", "Cargo binary crate with a unit test") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "Cargo.toml", """
                [package]
                name = "%s"
                version = "0.1.0"
                edition = "2021"
                """.formatted(name.toLowerCase().replaceAll("[^a-z0-9_-]", "-")));
            write(dir, "src/main.rs", """
                fn greet(name: &str) -> String {
                    format!("Hello, {name}!")
                }

                fn main() {
                    println!("{}", greet("NMOX"));
                }

                #[cfg(test)]
                mod tests {
                    use super::*;

                    #[test]
                    fn greets() {
                        assert_eq!(greet("rack"), "Hello, rack!");
                    }
                }
                """);
        }

        @Override
        JSONObject buildPatch() {
            return polyglotPatch();
        }

        @Override
        boolean lintable() {
            return false;
        }

        @Override
        boolean prettier() {
            return false;
        }

        @Override
        String gitignore() {
            return """
                target/
                """;
        }

        @Override
        String readmeHints() {
            return """
                - IGNITE on IGNITION runs `cargo run`; VERITAS runs `cargo test`
                - FORGE builds (PROD flips on --release)
                - arm REFLEX's WATCH switch for a save-driven test loop
                """;
        }
    },

    ANGULAR("Angular (standalone)", "Angular 22, zoneless, signals + control flow, HALO-wired") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "package.json", """
                {
                  "name": "%s",
                  "version": "0.1.0",
                  "private": true,
                  "scripts": {
                    "ng": "ng",
                    "start": "ng serve",
                    "build": "ng build",
                    "test": "ng test"
                  },
                  "dependencies": {
                    "@angular/common": "^22.0.0",
                    "@angular/compiler": "^22.0.0",
                    "@angular/core": "^22.0.0",
                    "@angular/platform-browser": "^22.0.0",
                    "@angular/router": "^22.0.0",
                    "rxjs": "~7.8.0",
                    "tslib": "^2.8.0"
                  },
                  "devDependencies": {
                    "@angular/build": "^22.0.0",
                    "@angular/cli": "^22.0.0",
                    "@angular/compiler-cli": "^22.0.0",
                    "typescript": "~5.9.0"
                  }
                }
                """.formatted(name));
            write(dir, "angular.json", """
                {
                  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
                  "version": 1,
                  "projects": {
                    "%s": {
                      "projectType": "application",
                      "root": "",
                      "sourceRoot": "src",
                      "prefix": "app",
                      "architect": {
                        "build": {
                          "builder": "@angular/build:application",
                          "options": {
                            "outputPath": "dist/%s",
                            "index": "src/index.html",
                            "browser": "src/main.ts",
                            "tsConfig": "tsconfig.app.json",
                            "styles": ["src/styles.css"]
                          },
                          "configurations": {
                            "production": {"outputHashing": "all"},
                            "development": {"optimization": false, "sourceMap": true}
                          },
                          "defaultConfiguration": "production"
                        },
                        "serve": {
                          "builder": "@angular/build:dev-server",
                          "configurations": {
                            "production": {"buildTarget": "%s:build:production"},
                            "development": {"buildTarget": "%s:build:development"}
                          },
                          "defaultConfiguration": "development"
                        },
                        "test": {
                          "builder": "@angular/build:unit-test"
                        }
                      }
                    }
                  }
                }
                """.formatted(name, name, name, name));
            write(dir, "tsconfig.json", """
                {
                  "compileOnSave": false,
                  "compilerOptions": {
                    "strict": true,
                    "noImplicitOverride": true,
                    "noPropertyAccessFromIndexSignature": true,
                    "noImplicitReturns": true,
                    "noFallthroughCasesInSwitch": true,
                    "skipLibCheck": true,
                    "isolatedModules": true,
                    "experimentalDecorators": false,
                    "moduleResolution": "bundler",
                    "importHelpers": true,
                    "target": "ES2022",
                    "module": "preserve"
                  },
                  "angularCompilerOptions": {
                    "enableI18nLegacyMessageIdFormat": false,
                    "strictInjectionParameters": true,
                    "strictInputAccessModifiers": true,
                    "typeCheckHostBindings": true,
                    "strictTemplates": true
                  }
                }
                """);
            write(dir, "tsconfig.app.json", """
                {
                  "extends": "./tsconfig.json",
                  "compilerOptions": {"outDir": "./out-tsc/app", "types": []},
                  "files": ["src/main.ts"],
                  "include": ["src/**/*.d.ts"]
                }
                """);
            write(dir, "src/index.html", """
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <title>%s</title>
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                </head>
                <body>
                  <app-root></app-root>
                </body>
                </html>
                """.formatted(name));
            write(dir, "src/styles.css", """
                :root { color-scheme: dark; }
                body {
                  margin: 0;
                  font-family: system-ui, sans-serif;
                  background: #1b1b1f;
                  color: #e6e7eb;
                  display: grid;
                  place-items: center;
                  min-height: 100vh;
                }
                """);
            write(dir, "src/main.ts", """
                import { bootstrapApplication } from '@angular/platform-browser';
                import { appConfig } from './app/app.config';
                import { App } from './app/app';

                bootstrapApplication(App, appConfig).catch(err => console.error(err));
                """);
            write(dir, "src/app/app.config.ts", """
                import { ApplicationConfig, provideZonelessChangeDetection } from '@angular/core';
                import { provideRouter } from '@angular/router';
                import { routes } from './app.routes';

                export const appConfig: ApplicationConfig = {
                  providers: [provideZonelessChangeDetection(), provideRouter(routes)],
                };
                """);
            write(dir, "src/app/app.routes.ts", """
                import { Routes } from '@angular/router';

                export const routes: Routes = [];
                """);
            write(dir, "src/app/app.ts", """
                import { Component, computed, signal } from '@angular/core';

                @Component({
                  selector: 'app-root',
                  templateUrl: './app.html',
                  styleUrl: './app.css',
                })
                export class App {
                  readonly count = signal(0);
                  readonly doubled = computed(() => this.count() * 2);
                  readonly features = signal(['signals', 'zoneless', 'control flow']);

                  increment(): void {
                    this.count.update(v => v + 1);
                  }
                }
                """);
            write(dir, "src/app/app.html", """
                <main>
                  <h1>%s</h1>
                  <button (click)="increment()">count: {{ count() }}</button>
                  <p>doubled: {{ doubled() }}</p>
                  @if (count() > 4) {
                    <p>that's plenty.</p>
                  }
                  <ul>
                    @for (feature of features(); track feature) {
                      <li>{{ feature }}</li>
                    }
                  </ul>
                </main>
                """.formatted(name));
            write(dir, "src/app/app.css", """
                main { text-align: center; }
                button { font-size: 1.25rem; padding: 0.5rem 1.5rem; cursor: pointer; }
                """);
            write(dir, "src/app/app.spec.ts", """
                import { TestBed } from '@angular/core/testing';
                import { provideZonelessChangeDetection } from '@angular/core';
                import { App } from './app';

                describe('App', () => {
                  beforeEach(async () => {
                    await TestBed.configureTestingModule({
                      imports: [App],
                      providers: [provideZonelessChangeDetection()],
                    }).compileComponents();
                  });

                  it('creates and counts', () => {
                    const fixture = TestBed.createComponent(App);
                    const app = fixture.componentInstance;
                    expect(app).toBeTruthy();
                    app.increment();
                    expect(app.count()).toBe(1);
                  });
                });
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                RackDevice halo = add(rack, DeviceType.ANGULAR, Map.of("prod", "true"));
                RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
                RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
                RackDevice test = add(rack, DeviceType.TEST, null);
                RackDevice browser = add(rack, DeviceType.BROWSER, null);
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                rack.connect(halo.getPort("url"), browser.getPort("url"));
                rack.connect(halo.getPort("ready"), browser.getPort("open"));
                rack.connect(reflex.getPort("changed"), test.getPort("run"));
                rack.connect(test.getPort("out"), console.getPort("in"));
                rack.connect(halo.getPort("out"), console.getPort("in"));
            });
        }

        @Override
        boolean lintable() {
            return false; // angular-eslint arrives via `ng add angular-eslint`
        }

        @Override
        String readmeHints() {
            return """
                - press INSTALL on CRATE (or run `npm install`) once
                - SERVE on HALO runs ng serve and opens the browser via SCOPE
                - HALO's version cluster tracks the latest Angular; UPDATE runs `ng update`
                - GEN scaffolds components/services with the SCHEMATIC knob
                """;
        }
    },

    ELIXIR_MIX("Elixir (mix)", "Mix project with ExUnit, BEAM-wired rack") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            String module = toModuleName(name);
            write(dir, "mix.exs", """
                defmodule %s.MixProject do
                  use Mix.Project

                  def project do
                    [
                      app: :%s,
                      version: "0.1.0",
                      elixir: "~> 1.17",
                      start_permanent: Mix.env() == :prod,
                      deps: deps()
                    ]
                  end

                  def application do
                    [extra_applications: [:logger]]
                  end

                  defp deps do
                    []
                  end
                end
                """.formatted(module, snake(name)));
            write(dir, "lib/" + snake(name) + ".ex", """
                defmodule %s do
                  @moduledoc \"""
                  %s - generated by NMOX Studio.
                  \"""

                  @doc \"""
                  The obligatory greeting.

                  ## Examples

                      iex> %s.hello()
                      :world

                  \"""
                  def hello do
                    :world
                  end
                end
                """.formatted(module, module, module));
            write(dir, "test/" + snake(name) + "_test.exs", """
                defmodule %sTest do
                  use ExUnit.Case
                  doctest %s

                  test "greets the world" do
                    assert %s.hello() == :world
                  end
                end
                """.formatted(module, module, module));
            write(dir, "test/test_helper.exs", "ExUnit.start()\n");
            write(dir, ".formatter.exs", """
                [
                  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
                ]
                """);
        }

        @Override
        JSONObject buildPatch() {
            return buildPatchFrom(rack -> {
                RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
                RackDevice run = add(rack, DeviceType.RUN, null);
                RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
                RackDevice test = add(rack, DeviceType.TEST, null);
                RackDevice console = add(rack, DeviceType.CONSOLE, null);
                rack.connect(deps.getPort("ok"), test.getPort("run"));
                rack.connect(reflex.getPort("changed"), test.getPort("run"));
                rack.connect(test.getPort("out"), console.getPort("in"));
                rack.connect(run.getPort("out"), console.getPort("in"));
            });
        }

        @Override
        boolean lintable() {
            return false;
        }

        @Override
        boolean prettier() {
            return false; // .formatter.exs + mix format own this
        }

        @Override
        String gitignore() {
            return """
                _build/
                deps/
                *.beam
                erl_crash.dump
                """;
        }

        @Override
        String readmeHints() {
            return """
                - INSTALL on CRATE runs `mix deps.get`; VERITAS runs `mix test`
                - IGNITION runs `mix run --no-halt`
                - building a Phoenix app? `mix phx.new`, then rack the PHOENIX console
                """;
        }
    },

    PHP_WEB("PHP Web (LEMP)", "Plain PHP: composer + PHPUnit/PHPStan/Pint, nginx+fpm+MariaDB compose, droplet cloud-init") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            String pkg = name.toLowerCase().replaceAll("[^a-z0-9_.-]", "-");
            write(dir, "composer.json", """
                {
                  "name": "app/%s",
                  "description": "Generated by NMOX Studio (PHP Web LEMP template).",
                  "type": "project",
                  "require": {
                    "php": ">=8.2"
                  },
                  "require-dev": {
                    "phpunit/phpunit": "^11",
                    "phpstan/phpstan": "^2",
                    "laravel/pint": "^1"
                  },
                  "autoload": {
                    "psr-4": {
                      "App\\\\": "src/"
                    }
                  },
                  "autoload-dev": {
                    "psr-4": {
                      "App\\\\Tests\\\\": "tests/"
                    }
                  },
                  "scripts": {
                    "test": "phpunit",
                    "analyse": "phpstan analyse --no-progress",
                    "fmt": "pint",
                    "serve": "php -S 127.0.0.1:8000 -t public public/index.php"
                  }
                }
                """.formatted(pkg));
            write(dir, "public/index.php", """
                <?php

                declare(strict_types=1);

                // As the `php -S` router script (composer serve): hand real files
                // back to the built-in server, route everything else through here.
                if (PHP_SAPI === 'cli-server') {
                    $file = __DIR__ . (parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: '/');
                    if ($file !== __FILE__ && is_file($file)) {
                        return false;
                    }
                }

                // Composer's autoloader when present; the raw class file otherwise,
                // so the site answers before `composer install` has ever run.
                $autoload = __DIR__ . '/../vendor/autoload.php';
                if (is_file($autoload)) {
                    require $autoload;
                } else {
                    require __DIR__ . '/../src/Greeting.php';
                }

                $path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';

                switch ($path) {
                    case '/api/health':
                        header('Content-Type: application/json');
                        echo json_encode(['ok' => true]);
                        break;

                    case '/':
                        $greeting = (new App\\Greeting())->hello('%s');
                        header('Content-Type: text/html; charset=utf-8');
                        echo <<<HTML
                        <!doctype html>
                        <html lang="en">
                          <head>
                            <meta charset="utf-8" />
                            <meta name="viewport" content="width=device-width, initial-scale=1" />
                            <title>%s</title>
                          </head>
                          <body style="font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto">
                            <h1>{$greeting}</h1>
                            <p>Generated by NMOX Studio. Edit <code>public/index.php</code> and save.</p>
                            <p><a href="/api/health">/api/health</a></p>
                          </body>
                        </html>
                        HTML;
                        break;

                    default:
                        http_response_code(404);
                        header('Content-Type: application/json');
                        echo json_encode(['error' => 'not found']);
                }
                """.formatted(name, name));
            write(dir, "src/Greeting.php", """
                <?php

                declare(strict_types=1);

                namespace App;

                /** Generated by NMOX Studio. */
                final class Greeting
                {
                    public function hello(string $who): string
                    {
                        return "Hello, {$who}!";
                    }
                }
                """);
            write(dir, "tests/GreetingTest.php", """
                <?php

                declare(strict_types=1);

                namespace App\\Tests;

                use App\\Greeting;
                use PHPUnit\\Framework\\TestCase;

                final class GreetingTest extends TestCase
                {
                    public function testGreetsByName(): void
                    {
                        $this->assertSame('Hello, rack!', (new Greeting())->hello('rack'));
                    }

                    public function testAlwaysGreets(): void
                    {
                        $this->assertStringStartsWith('Hello', (new Greeting())->hello(''));
                    }
                }
                """);
            write(dir, "phpunit.xml", """
                <?xml version="1.0" encoding="UTF-8"?>
                <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         bootstrap="vendor/autoload.php"
                         colors="true">
                    <testsuites>
                        <testsuite name="tests">
                            <directory>tests</directory>
                        </testsuite>
                    </testsuites>
                    <source>
                        <include>
                            <directory>src</directory>
                        </include>
                    </source>
                </phpunit>
                """);
            write(dir, "phpstan.neon.dist", """
                parameters:
                    level: 6
                    paths:
                        - src
                        - tests
                """);
            write(dir, ".env.example", """
                APP_ENV=local
                DB_HOST=127.0.0.1
                DB_PORT=3306
                DB_DATABASE=app
                DB_USERNAME=app
                DB_PASSWORD=secret
                """);
            write(dir, "docker-compose.yml", """
                # The local LEMP stack. DB_* values interpolate from .env when
                # present (copy .env.example); the :-defaults keep first
                # `docker compose up` working without one.
                services:
                  nginx:
                    image: nginx:1.27-alpine
                    ports:
                      - "8080:80"
                    volumes:
                      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
                      - .:/var/www/html:ro
                    depends_on:
                      - php

                  php:
                    image: php:8.3-fpm
                    working_dir: /var/www/html
                    volumes:
                      - .:/var/www/html

                  db:
                    image: mariadb:11
                    environment:
                      MARIADB_DATABASE: ${DB_DATABASE:-app}
                      MARIADB_USER: ${DB_USERNAME:-app}
                      MARIADB_PASSWORD: ${DB_PASSWORD:-secret}
                      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
                    ports:
                      - "3306:3306"
                    volumes:
                      - db-data:/var/lib/mysql

                volumes:
                  db-data:
                """);
            write(dir, "docker/nginx.conf", """
                # Front-controller server block: real files first, index.php for
                # the rest. PHP hands off to the fpm container over FastCGI.
                server {
                    listen 80;
                    server_name _;

                    root /var/www/html/public;
                    index index.php;

                    location / {
                        try_files $uri $uri/ /index.php?$query_string;
                    }

                    location ~ \\.php$ {
                        include fastcgi_params;
                        fastcgi_pass php:9000;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    }
                }
                """);
            write(dir, "deploy/cloud-init.yml", """
                #cloud-config
                # LEMP bootstrap for a fresh Ubuntu droplet. Paste this file into
                # the droplet's USER DATA field in the Infra designer (or use
                # `doctl compute droplet create --user-data-file deploy/cloud-init.yml`),
                # then rsync/git your app into /var/www/html.
                package_update: true
                packages:
                  - nginx
                  - php-fpm
                  - php-mysql
                  - php-cli
                  - php-xml
                  - php-mbstring
                  - mariadb-server
                  - composer
                  - git

                write_files:
                  # The same front-controller server block the local compose uses,
                  # pointed at the distro's php-fpm socket instead of a container.
                  - path: /etc/nginx/sites-available/app
                    content: |
                      server {
                          listen 80 default_server;
                          server_name _;

                          root /var/www/html/public;
                          index index.php;

                          location / {
                              try_files $uri $uri/ /index.php?$query_string;
                          }

                          location ~ \\.php$ {
                              include snippets/fastcgi-php.conf;
                              fastcgi_pass unix:/run/php/php-fpm.sock;
                          }
                      }

                runcmd:
                  # Ubuntu ships the fpm unit and socket with the PHP version in
                  # the name; find them so this file survives version bumps.
                  - sh -c 'systemctl enable --now "$(basename "$(ls /lib/systemd/system/php*-fpm.service | head -1)")"'
                  - sh -c 'ln -sf /run/php/php*-fpm.sock /run/php/php-fpm.sock'
                  - systemctl enable --now nginx mariadb
                  # wire the site in, drop the stock default page, reload
                  - mkdir -p /var/www/html/public
                  - ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
                  - rm -f /etc/nginx/sites-enabled/default
                  - systemctl reload nginx
                """);
        }

        @Override
        JSONObject buildPatch() {
            // the LAMP Bench preset IS this template's wiring - one definition
            return RackPresets.LAMP_BENCH.buildPatch();
        }

        @Override
        boolean lintable() {
            return false;
        }

        @Override
        boolean prettier() {
            return false; // GLOSS runs Laravel Pint on PHP lanes
        }

        @Override
        String gitignore() {
            return """
                vendor/
                .env
                .phpunit.cache/
                """;
        }

        @Override
        String readmeHints() {
            return """
                - press INSTALL on CRATE (or run `composer install`) once
                - IGNITE on IGNITION serves `public/` at http://127.0.0.1:8000; `composer serve`
                  adds front-controller routing for `/api/*` under the built-in server
                - VERITAS runs phpunit, TYPEGUARD runs phpstan, GLOSS checks Laravel Pint
                - `docker compose up` boots the full LEMP stack: nginx on :8080 -> php-fpm -> MariaDB
                - to deploy: paste `deploy/cloud-init.yml` into a droplet's user_data in the Infra designer
                """;
        }
    },

    CLASSIC_WEB_JQUERY("Classic Web (jQuery)",
            "script-tag era, no build step — served as-is") {
        @Override
        void writeFiles(Path dir, String name) throws IOException {
            write(dir, "index.html", """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <title>%s</title>
                  <link rel="stylesheet" href="css/style.css">
                  <script src="vendor/jquery-3.7.1.min.js"></script>
                  <script src="js/app.js"></script>
                </head>
                <body>
                  <div id="header">
                    <h1>%s</h1>
                  </div>
                  <div id="content">
                    <p>A classic page: jQuery from a plain script tag, no build step.</p>
                    <button id="clicker">clicks: 0</button>
                  </div>
                </body>
                </html>
                """.formatted(name, name));
            write(dir, "css/style.css", """
                body { font-family: Verdana, Geneva, sans-serif; margin: 0; }
                #header { background: #333; color: #fff; padding: 16px 24px; }
                #header h1 { margin: 0; font-size: 22px; }
                #content { max-width: 640px; margin: 32px auto; padding: 0 16px; }
                button { font: inherit; padding: 6px 14px; cursor: pointer; }
                """);
            write(dir, "js/app.js", """
                // The classic starting point: wait for the DOM, then wire things up.
                $(document).ready(function () {
                  var clicks = 0;
                  $('#clicker').on('click', function () {
                    clicks += 1;
                    $(this).text('clicks: ' + clicks);
                  });
                });
                """);
            // the bundled pinned build, byte for byte (see the Classic Kit's
            // NOTICE-vendor.md for provenance and SHA-256)
            Path vendored = dir.resolve("vendor/jquery-3.7.1.min.js");
            Files.createDirectories(vendored.getParent());
            Files.write(vendored, ClassicKit.vendorBytes("jquery-3.7.1.min.js"));
        }

        @Override
        JSONObject buildPatch() {
            // the Classic Web Bench preset IS this template's wiring - one definition
            return RackPresets.CLASSIC_WEB.buildPatch();
        }

        @Override
        boolean lintable() {
            return false; // no package.json — nothing to hold an eslint dep
        }

        @Override
        boolean prettier() {
            return false; // script-tag era: no Node toolchain at all
        }

        @Override
        String gitignore() {
            // vendor/ is deliberately NOT ignored: pinned files committed
            // alongside the code are this era's lockfile
            return """
                dist/
                bower_components/
                .env
                """;
        }

        @Override
        String readmeHints() {
            return """
                - no install, no build: index.html loads `vendor/jquery-3.7.1.min.js` from a
                  plain script tag and `js/app.js` does its work in $(document).ready
                - IGNITE on IGNITION serves this folder statically and VITALS scores the page
                - DYNAMO runs taskfiles: add a Gruntfile.js or gulpfile.js (File → Classic
                  Kit…) and its tasks appear on the knob
                - `vendor/` is committed on purpose — pinned files are the era's lockfile
                """;
        }
    };

    private final String displayName;
    private final String description;

    ProjectTemplates(String displayName, String description) {
        this.displayName = displayName;
        this.description = description;
    }

    public String getDisplayName() {
        return displayName;
    }

    public String getDescription() {
        return description;
    }

    /** my-app -> MyApp, for Elixir module names. */
    static String toModuleName(String name) {
        StringBuilder sb = new StringBuilder();
        for (String part : name.split("[-_\\s]+")) {
            if (!part.isEmpty()) {
                sb.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        return sb.isEmpty() ? "App" : sb.toString();
    }

    /** my-app -> my_app, for Elixir app atoms and file names. */
    static String snake(String name) {
        return name.toLowerCase().replaceAll("[-\\s]+", "_").replaceAll("[^a-z0-9_]", "");
    }

    abstract void writeFiles(Path dir, String name) throws IOException;

    abstract JSONObject buildPatch();

    /** Per-template .gitignore; default fits Node toolchains. */
    String gitignore() {
        return """
            node_modules/
            dist/
            coverage/
            .env
            """;
    }

    /** Whether the template ships a .prettierrc (Node toolchains do). */
    boolean prettier() {
        return true;
    }

    /** README quick-start bullet lines (each ends with a newline). */
    String readmeHints() {
        return """
            - press INSTALL on CRATE (or run `npm install`) once
            - START on SURGE serves the project and opens the browser
            - arm REFLEX's WATCH switch for a save-driven test loop
            """;
    }

    /** Whether the generated project gets an eslint flat config. */
    boolean lintable() {
        return true;
    }

    /**
     * Generates the project into {@code dir} (created; must not already
     * contain files): sources, package.json, .gitignore, README, and the
     * pre-wired rack patch.
     */
    /**
     * Every real project starts versioned: init a repo and lay down the
     * first commit so TIMELINE and the platform's git colors work from
     * minute one. Best-effort - a machine without git still gets its
     * project, just unversioned.
     */
    public static void initGitRepo(File dir) {
        if (run(dir, "git", "init") != 0) {
            return;
        }
        run(dir, "git", "add", "-A");
        if (run(dir, "git", "commit", "-m", "Initial commit — scaffolded by NMOX Studio") != 0) {
            // no committer identity configured; commit with a local fallback
            run(dir, "git", "-c", "user.name=NMOX Studio", "-c", "user.email=studio@nmox.local",
                    "commit", "-m", "Initial commit — scaffolded by NMOX Studio");
        }
    }

    private static int run(File dir, String... cmd) {
        try {
            ProcessBuilder pb = org.nmox.studio.core.process.ProcessSupport
                    .builder(java.util.List.of(cmd))
                    .directory(dir)
                    .redirectErrorStream(true);
            Process proc = pb.start();
            proc.getInputStream().readAllBytes();
            return proc.waitFor(30, java.util.concurrent.TimeUnit.SECONDS) ? proc.exitValue() : -1;
        } catch (Exception ex) {
            return -1;
        }
    }

    public void generate(File dir, String name) throws IOException {
        Path root = dir.toPath();
        Files.createDirectories(root);
        try (var entries = Files.list(root)) {
            if (entries.findAny().isPresent()) {
                throw new IOException("Directory is not empty: " + dir);
            }
        }
        writeFiles(root, name);
        write(root, ".gitignore", gitignore());
        write(root, ".editorconfig", """
            root = true

            [*]
            charset = utf-8
            end_of_line = lf
            insert_final_newline = true
            indent_style = space
            indent_size = 2
            trim_trailing_whitespace = true
            """);
        if (prettier()) {
            write(root, ".prettierrc", """
                {
                  "singleQuote": true,
                  "semi": true,
                  "printWidth": 100
                }
                """);
        }
        if (lintable()) {
            write(root, "eslint.config.mjs", """
                import js from '@eslint/js';
                import globals from 'globals';

                export default [
                  js.configs.recommended,
                  {
                    languageOptions: {
                      globals: { ...globals.browser, ...globals.node },
                    },
                  },
                  { ignores: ['dist/', 'node_modules/', 'coverage/'] },
                ];
                """);
        }
        // the final %s shares the block's indentation so the stripping
        // actually happens - at column 0 it would pin every line's indent
        write(root, "README.md", """
            # %s

            Created with NMOX Studio (%s template).

            The Task Rack infra for this project lives in `.nmoxrack.json`
            and mounts automatically when the rack aims here:

            %s""".formatted(name, displayName, readmeHints()));
        Files.writeString(root.resolve(RackIO.DEFAULT_FILENAME),
                buildPatch().toString(2), StandardCharsets.UTF_8);
    }

    static void write(Path root, String relative, String content) throws IOException {
        Path target = root.resolve(relative);
        Files.createDirectories(target.getParent());
        Files.writeString(target, content, StandardCharsets.UTF_8);
    }

    /** Shared patch for the polyglot templates: run/test/debug, save-driven. */
    private static JSONObject polyglotPatch() {
        return buildPatchFrom(rack -> {
            RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
            RackDevice run = add(rack, DeviceType.RUN, null);
            RackDevice debug = add(rack, DeviceType.DEBUG, null);
            RackDevice test = add(rack, DeviceType.TEST, null);
            RackDevice console = add(rack, DeviceType.CONSOLE, null);
            rack.connect(reflex.getPort("changed"), test.getPort("run"));
            rack.connect(test.getPort("out"), console.getPort("in"));
            rack.connect(run.getPort("out"), console.getPort("in"));
            rack.connect(debug.getPort("out"), console.getPort("in"));
        });
    }

    /** Shared patch for the Vite-based templates (React/Vue). */
    private static JSONObject vitePatch() {
        return buildPatchFrom(rack -> {
            RackDevice master = add(rack, DeviceType.MASTER, null);
            RackDevice reflex = add(rack, DeviceType.REFLEX, Map.of("armed", "false", "filter", "1"));
            RackDevice deps = add(rack, DeviceType.PACKAGE_MANAGER, null);
            // vite on 5173
            RackDevice server = add(rack, DeviceType.DEV_SERVER, Map.of("server", "1", "port", "2"));
            RackDevice browser = add(rack, DeviceType.BROWSER, Map.of("url", "http://localhost:5173"));
            RackDevice build = add(rack, DeviceType.BUILD, Map.of("tool", "1"));
            RackDevice test = add(rack, DeviceType.TEST, Map.of("framework", "2"));
            RackDevice console = add(rack, DeviceType.CONSOLE, null);

            // CI lane
            rack.connect(master.getPort("trig1"), deps.getPort("run"));
            rack.connect(deps.getPort("ok"), build.getPort("run"));
            rack.connect(build.getPort("ok"), test.getPort("run"));
            rack.connect(test.getPort("out"), console.getPort("in"));
            // dev lane
            rack.connect(server.getPort("url"), browser.getPort("url"));
            rack.connect(server.getPort("ready"), browser.getPort("open"));
            // TDD lane (arm REFLEX to activate)
            rack.connect(reflex.getPort("changed"), test.getPort("run"));
        });
    }
}
