package org.nmox.studio.rack.projectstudio;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 * The PWA Kit: everything a project needs to install and work offline
 * - an installability-complete W3C manifest (with maskable icons), the
 * icon set itself via {@link IconForge}, a readable vanilla service
 * worker whose precache list is built from the files the project
 * actually has, an offline fallback page, and idempotent wiring of
 * index.html's head. Pure builders so every claim is testable; the
 * wizard in the File menu drives {@link #write}.
 */
public final class PwaKit {

    private PwaKit() {
    }

    /** How the service worker answers fetches. */
    public enum Strategy {
        /** Cache first: instant loads, offline-ready; bump CACHE to ship changes. */
        APP_SHELL,
        /** Network first: always-fresh content, cache as the fallback. */
        NETWORK_FIRST
    }

    /** What the wizard collected. */
    public record Options(String name, String shortName, String themeColor,
            String backgroundColor, String monogram, File artwork,
            Strategy strategy, boolean icons, boolean manifest,
            boolean serviceWorker, boolean wireIndex) {
    }

    /** One touched (or skipped) file, for the wizard's report. */
    public record Outcome(String path, String status) {

        public boolean written() {
            return "written".equals(status) || "wired".equals(status);
        }
    }

    private static final Pattern HEX_COLOR
            = Pattern.compile("#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?");

    /** Only a real hex color enters generated markup; anything else falls back. */
    static String safeColor(String value, String fallback) {
        return value != null && HEX_COLOR.matcher(value.strip()).matches()
                ? value.strip().toLowerCase(Locale.ROOT) : fallback;
    }

    /** Free-text wizard fields are escaped before they enter generated HTML. */
    static String escapeHtml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    static final String[] ICON_FILES = {
        "icon-192.png", "icon-512.png",
        "icon-maskable-192.png", "icon-maskable-512.png",
        "apple-touch-icon.png"
    };

    /**
     * W3C Web App Manifest, installability-complete: both purposes of
     * icon (any + maskable), scope, and the display/color members.
     */
    public static String manifest(Options opts) {
        JSONObject m = new JSONObject();
        m.put("name", opts.name());
        m.put("short_name", opts.shortName().length() > 12
                ? opts.shortName().substring(0, 12) : opts.shortName());
        m.put("start_url", "/");
        m.put("scope", "/");
        m.put("display", "standalone");
        m.put("background_color", safeColor(opts.backgroundColor(), "#1a1a1e"));
        m.put("theme_color", safeColor(opts.themeColor(), "#1a1a1e"));
        JSONArray icons = new JSONArray();
        icons.put(icon("/icon-192.png", "192x192", "any"));
        icons.put(icon("/icon-512.png", "512x512", "any"));
        icons.put(icon("/icon-maskable-192.png", "192x192", "maskable"));
        icons.put(icon("/icon-maskable-512.png", "512x512", "maskable"));
        m.put("icons", icons);
        return m.toString(2) + "\n";
    }

    private static JSONObject icon(String src, String sizes, String purpose) {
        return new JSONObject().put("src", src).put("sizes", sizes)
                .put("type", "image/png").put("purpose", purpose);
    }

    /**
     * The service worker, written to be read: versioned cache,
     * precache on install, stale-cache cleanup on activate, and the
     * chosen fetch strategy. GET-only, same-origin caching, offline
     * fallback for navigations.
     */
    public static String serviceWorker(List<String> precache, Strategy strategy) {
        StringBuilder list = new StringBuilder();
        for (String p : precache) {
            list.append("  '")
                    .append(p.replace("\\", "\\\\").replace("'", "\\'"))
                    .append("',\n");
        }
        String header = """
                // sw.js — generated by NMOX Studio. Edit freely; bump CACHE to ship changes.
                const CACHE = 'nmox-pwa-v1';
                const PRECACHE = [
                %s];

                self.addEventListener('install', (event) => {
                  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
                  self.skipWaiting();
                });

                self.addEventListener('activate', (event) => {
                  event.waitUntil(
                    caches.keys()
                      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
                      .then(() => self.clients.claim())
                  );
                });
                """.formatted(list);
        String fetch = strategy == Strategy.APP_SHELL ? """

                // App shell: cache first — instant loads, offline-ready.
                self.addEventListener('fetch', (event) => {
                  const { request } = event;
                  if (request.method !== 'GET' || !request.url.startsWith('http')) return;
                  event.respondWith(
                    caches.match(request).then(
                      (hit) => hit || fetch(request)
                        .then((response) => {
                          if (response.ok && new URL(request.url).origin === self.location.origin) {
                            const copy = response.clone();
                            caches.open(CACHE).then((cache) => cache.put(request, copy));
                          }
                          return response;
                        })
                        .catch(() => (request.mode === 'navigate'
                          ? caches.match('/offline.html')
                          : Response.error()))
                    )
                  );
                });
                """ : """

                // Network first: always-fresh content, cache as the fallback.
                self.addEventListener('fetch', (event) => {
                  const { request } = event;
                  if (request.method !== 'GET' || !request.url.startsWith('http')) return;
                  event.respondWith(
                    fetch(request)
                      .then((response) => {
                        if (response.ok && new URL(request.url).origin === self.location.origin) {
                          const copy = response.clone();
                          caches.open(CACHE).then((cache) => cache.put(request, copy));
                        }
                        return response;
                      })
                      .catch(() => caches.match(request).then(
                        (hit) => hit || (request.mode === 'navigate'
                          ? caches.match('/offline.html')
                          : Response.error())
                      ))
                  );
                });
                """;
        return header + fetch;
    }

    /** The offline fallback page the service worker serves to navigations. */
    public static String offlineHtml(Options opts) {
        return """
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <meta name="viewport" content="width=device-width, initial-scale=1">
                  <title>%1$s — offline</title>
                  <style>
                    body { margin: 0; min-height: 100vh; display: grid; place-items: center;
                           background: %2$s; color: #fff;
                           font-family: system-ui, sans-serif; text-align: center; }
                    p { opacity: .7 }
                  </style>
                </head>
                <body>
                  <div>
                    <h1>%1$s is offline</h1>
                    <p>No connection right now — this page will work again when you're back online.</p>
                  </div>
                </body>
                </html>
                """.formatted(escapeHtml(opts.name()), safeColor(opts.themeColor(), "#1a1a1e"));
    }

    /**
     * Builds the precache list from the files the project actually
     * has: top-level pages, styles, and scripts, plus the manifest and
     * icons this kit writes. The service worker itself never precaches
     * itself.
     */
    public static List<String> precacheList(File projectDir, Options opts) {
        List<String> out = new ArrayList<>();
        out.add("/");
        File[] files = projectDir.listFiles();
        if (files != null) {
            List<File> sorted = new ArrayList<>(List.of(files));
            sorted.sort(Comparator.comparing(File::getName));
            for (File f : sorted) {
                String n = f.getName().toLowerCase(Locale.ROOT);
                // tool configs (eslint.config.mjs, vite.config.js, ...) are
                // dev-time files, not app content
                if (!f.isFile() || n.equals("sw.js") || n.startsWith(".")
                        || n.contains(".config.")) {
                    continue;
                }
                if (n.endsWith(".html") || n.endsWith(".css") || n.endsWith(".js")
                        || n.endsWith(".mjs") || n.equals("site.webmanifest")) {
                    out.add("/" + f.getName());
                }
            }
        }
        if (opts.serviceWorker() && !out.contains("/offline.html")) {
            out.add("/offline.html");
        }
        if (opts.manifest() && !out.contains("/site.webmanifest")) {
            out.add("/site.webmanifest");
        }
        if (opts.icons()) {
            out.add("/icon-192.png");
            out.add("/icon-512.png");
        }
        return out;
    }

    /**
     * Wires index.html's head - manifest link, theme-color meta,
     * apple-touch-icon link, service worker registration - inserting
     * only the pieces that aren't already there (via the shared
     * {@link HtmlWiring} seam). Running it twice changes nothing.
     */
    public static String wireHead(String html, Options opts) {
        StringBuilder add = new StringBuilder();
        if (opts.manifest() && !html.contains("rel=\"manifest\"")) {
            add.append("  <link rel=\"manifest\" href=\"/site.webmanifest\">\n");
        }
        if (!html.contains("name=\"theme-color\"")) {
            add.append("  <meta name=\"theme-color\" content=\"")
                    .append(safeColor(opts.themeColor(), "#1a1a1e")).append("\">\n");
        }
        if (opts.icons() && !html.contains("apple-touch-icon")) {
            add.append("  <link rel=\"apple-touch-icon\" href=\"/apple-touch-icon.png\">\n");
        }
        if (opts.serviceWorker() && !html.contains("serviceWorker")) {
            add.append("""
                      <script>
                        if ('serviceWorker' in navigator) {
                          addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));
                        }
                      </script>
                    """);
        }
        return HtmlWiring.insertBeforeHeadClose(html, add.toString());
    }

    /**
     * Writes the selected pieces into the project (generated files are
     * never overwritten; index.html wiring is the one edit, and it is
     * idempotent). Returns what happened, file by file.
     */
    public static List<Outcome> write(File projectDir, Options opts) throws IOException {
        List<Outcome> outcomes = new ArrayList<>();
        if (opts.icons()) {
            IconForge.Source source = opts.artwork() != null
                    ? new IconForge.Artwork(IconForge.read(opts.artwork()),
                            IconForge.color(opts.backgroundColor(), java.awt.Color.DARK_GRAY))
                    : new IconForge.Monogram(opts.monogram(),
                            IconForge.color(opts.themeColor(), java.awt.Color.DARK_GRAY),
                            java.awt.Color.WHITE);
            outcomes.add(writeIcon(projectDir, "icon-192.png", source, 192, false));
            outcomes.add(writeIcon(projectDir, "icon-512.png", source, 512, false));
            outcomes.add(writeIcon(projectDir, "icon-maskable-192.png", source, 192, true));
            outcomes.add(writeIcon(projectDir, "icon-maskable-512.png", source, 512, true));
            outcomes.add(writeIcon(projectDir, "apple-touch-icon.png", source, 180, true));
        }
        if (opts.manifest()) {
            outcomes.add(writeOne(projectDir, "site.webmanifest", manifest(opts)));
        }
        if (opts.serviceWorker()) {
            outcomes.add(writeOne(projectDir, "sw.js",
                    serviceWorker(precacheList(projectDir, opts), opts.strategy())));
            outcomes.add(writeOne(projectDir, "offline.html", offlineHtml(opts)));
        }
        if (opts.wireIndex()) {
            outcomes.add(wireIndex(projectDir, opts));
        }
        return outcomes;
    }

    private static Outcome writeIcon(File dir, String name, IconForge.Source source,
            int size, boolean fullBleed) throws IOException {
        File target = new File(dir, name);
        if (target.exists()) {
            return new Outcome(name, "already exists, untouched");
        }
        BufferedImage image = IconForge.render(source, size, fullBleed);
        IconForge.writePng(image, target);
        return new Outcome(name, "written");
    }

    private static Outcome writeOne(File dir, String name, String content) throws IOException {
        File target = new File(dir, name);
        if (target.exists()) {
            return new Outcome(name, "already exists, untouched");
        }
        Files.writeString(target.toPath(), content, StandardCharsets.UTF_8);
        return new Outcome(name, "written");
    }

    private static Outcome wireIndex(File dir, Options opts) throws IOException {
        File index = new File(dir, "index.html");
        if (!index.isFile()) {
            return new Outcome("index.html", "skipped — no index.html");
        }
        String before = Files.readString(index.toPath(), StandardCharsets.UTF_8);
        String after = wireHead(before, opts);
        if (after.equals(before)) {
            return new Outcome("index.html", "already wired");
        }
        Files.writeString(index.toPath(), after, StandardCharsets.UTF_8);
        return new Outcome("index.html", "wired");
    }
}
