package org.nmox.studio.rack.service;

import java.awt.Component;
import java.awt.Container;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.json.JSONObject;
import org.nmox.studio.core.spi.ProjectAim;
import org.nmox.studio.rack.devices.DeviceType;
import org.nmox.studio.rack.engine.RackBus;
import org.nmox.studio.rack.model.RackDevice;
import org.nmox.studio.rack.model.RackIO;
import org.nmox.studio.rack.projectstudio.ExperimentGuide;
import org.nmox.studio.rack.projectstudio.Experiments;
import org.nmox.studio.rack.projectstudio.LearningCatalog;
import org.nmox.studio.rack.projectstudio.LearningSpace;
import org.nmox.studio.rack.projectstudio.ProjectTemplates;
import org.nmox.studio.rack.projectstudio.RackPresets;
import org.nmox.studio.rack.ui.RackPanel;
import org.nmox.studio.rack.ui.controls.LcdDisplay;
import org.nmox.studio.rack.ui.controls.Led;
import org.nmox.studio.rack.ui.controls.RackButton;
import org.openide.cookies.OpenCookie;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.loaders.DataObject;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * The docs forge's staging hands (v2.162.0). The six hand-staged shots in
 * the user guide — a racked project, its rear, an open file, an experiment
 * with its walkthrough, KVASIR explaining a failure, the learning-space
 * shelf — were photographed once, in English, from a real session. A
 * translated guide needs the same states painted in its own language, so
 * the forge stages them itself: fixtures generated by the product's own
 * templates and presets under the forge's throwaway home, a failed run fed
 * to the flight recorder the way a real run's lines arrive, KVASIR's
 * EXPLAIN pressed through its accessible action.
 *
 * <p>Forge-only: every method here is reached from {@code DocsShots} under
 * {@code -Dnmox.shots.dir} and never on a normal boot. Deliberately NOT
 * {@code Experiments.create} / {@code LearningSpace.create}: those pre-trust
 * their roots in the JVM-global Workspace Trust store, which would leave a
 * throwaway forge path trusted in the developer's real preferences. The
 * marker files are written here in the exact shape the product's own
 * readers parse ({@link Experiments#info}, {@link LearningSpace#info}),
 * pinned by {@code DocsStagingTest}.
 */
public final class DocsStaging {

    /** The classic site's name — the rack and editor shots aim here. */
    public static final String CLASSIC_NAME = "classic-demo";
    /** The experiment's name — the walkthrough and KVASIR shots aim here. */
    public static final String EXPERIMENT_NAME = "hello-api";
    /** The bus name of the device whose failed run KVASIR explains. */
    public static final String FAILING_DEVICE = "VERITAS";

    private DocsStaging() {
    }

    /**
     * A Classic Web (jQuery) site under {@code <home>/NMOX/classic-demo}
     * carrying the Classic Web Bench preset as its patch, so aiming it
     * mounts MAESTRO, CRATE, DYNAMO, IGNITION and VITALS front and rear.
     */
    public static File classicSite(File home) throws IOException {
        File dir = new File(new File(home, "NMOX"), CLASSIC_NAME);
        if (!new File(dir, "index.html").isFile()) {
            Files.createDirectories(dir.toPath());
            ProjectTemplates.CLASSIC_WEB_JQUERY.generate(dir, CLASSIC_NAME);
        }
        writePatch(dir, RackPresets.CLASSIC_WEB.buildPatch());
        return dir;
    }

    /**
     * An Express API experiment under {@code <home>/.nmox/experiments/hello-api}
     * with the walkthrough the product writes at creation and a patch of
     * VERITAS → KVASIR → MONITOR, the rack the guide's KVASIR shot shows.
     */
    public static File expressExperiment(File home) throws IOException {
        File dir = new File(new File(new File(home, ".nmox"), "experiments"), EXPERIMENT_NAME);
        if (!new File(dir, "package.json").isFile()) {
            Files.createDirectories(dir.toPath());
            ProjectTemplates.EXPRESS_API.generate(dir, EXPERIMENT_NAME);
        }
        Files.writeString(new File(dir, Experiments.MARKER).toPath(),
                "created=" + java.time.LocalDate.now() + "\ntemplate="
                        + ProjectTemplates.EXPRESS_API.name() + "\n", StandardCharsets.UTF_8);
        Files.writeString(new File(dir, Experiments.GUIDE).toPath(),
                ExperimentGuide.walkthrough(ProjectTemplates.EXPRESS_API, EXPERIMENT_NAME),
                StandardCharsets.UTF_8);
        writePatch(dir, RackPresets.buildPatchFrom(rack -> {
            RackDevice test = RackPresets.add(rack, DeviceType.TEST, null);
            RackDevice kvasir = RackPresets.add(rack, DeviceType.KVASIR, null);
            RackDevice console = RackPresets.add(rack, DeviceType.CONSOLE, null);
            rack.connect(test.getPort("fail"), kvasir.getPort("explain"));
            rack.connect(test.getPort("out"), console.getPort("in"));
        }));
        return dir;
    }

    /**
     * Seeds {@code <home>/.nmox/learn} with catalogue spaces, each marker
     * dated {@code daysAgo} days back so the shelf reads a lived-in
     * lifecycle rather than six rows created "today". The names come from
     * the catalogue under the running locale, so a translated build's
     * shelf lists the spaces in its own words. Unknown slugs are skipped.
     */
    public static List<File> seedLearningSpaces(File home, Map<String, Integer> slugsToDaysAgo)
            throws IOException {
        List<File> out = new ArrayList<>();
        File root = new File(new File(home, ".nmox"), "learn");
        for (Map.Entry<String, Integer> e : slugsToDaysAgo.entrySet()) {
            LearningCatalog.Space space = LearningCatalog.find(e.getKey());
            if (space == null) {
                continue;
            }
            File dir = new File(root, space.slug());
            Files.createDirectories(dir.toPath());
            Files.writeString(new File(dir, LearningSpace.MARKER).toPath(),
                    "slug=" + space.slug() + "\nname=" + space.name() + "\ncreated="
                            + java.time.LocalDate.now().minusDays(Math.max(0, e.getValue())) + "\n",
                    StandardCharsets.UTF_8);
            for (LearningCatalog.SampleFile f : space.files()) {
                File target = new File(dir, f.path());
                if (!target.getCanonicalPath().startsWith(dir.getCanonicalPath() + File.separator)) {
                    continue; // never write outside the space, even for a built-in
                }
                Files.createDirectories(target.getParentFile().toPath());
                Files.writeString(target.toPath(), f.content(), StandardCharsets.UTF_8);
            }
            Files.writeString(new File(dir, "TUTORIAL.md").toPath(),
                    "# " + space.name() + "\n", StandardCharsets.UTF_8);
            out.add(dir);
        }
        return out;
    }

    /** Aims the studio (rack, Workbench, Project Studio) at a directory. */
    public static boolean aim(File dir) {
        ProjectAim aim = ProjectAim.find();
        if (aim == null) {
            return false;
        }
        aim.aim(dir);
        return true;
    }

    /** Opens a file in the editor exactly as a double-click in the tree would. */
    public static boolean openFile(File file) {
        try {
            FileObject fo = FileUtil.toFileObject(FileUtil.normalizeFile(file));
            if (fo == null) {
                return false;
            }
            OpenCookie open = DataObject.find(fo).getLookup().lookup(OpenCookie.class);
            if (open == null) {
                return false;
            }
            open.open();
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    /** Turns the rack around (the Rear (Tab) toggle); false when no rack window is open. */
    public static boolean flipRack() {
        TopComponent tc = WindowManager.getDefault().findTopComponent("RackTopComponent");
        RackPanel panel = tc == null ? null : find(tc, RackPanel.class, null);
        if (panel == null) {
            return false;
        }
        panel.flip();
        return true;
    }

    /**
     * Feeds one failed run through the bus in the exact shape a real run's
     * lines arrive ({@code $ command}, error lines, {@code [exit N]}), so the
     * flight recorder holds a LAUNCH, its errors and an EXIT_FAIL — the
     * record KVASIR reads — and MONITOR, which taps the bus, paints them.
     */
    public static void seedFailedRun(String device, String command, List<String> errorLines, int exitCode) {
        RackBus.publish(device, "$ " + command, false);
        for (String line : errorLines) {
            RackBus.publish(device, line, true);
        }
        RackBus.publish(device, "[exit " + exitCode + "]", false);
    }

    /** Presses KVASIR's EXPLAIN through its accessible action; false when no KVASIR is racked. */
    public static boolean pressKvasirExplain() {
        RackDevice kvasir = kvasir();
        RackButton explain = kvasir == null ? null : find(kvasir, RackButton.class, "EXPLAIN");
        if (explain == null) {
            return false;
        }
        javax.accessibility.AccessibleAction action = explain.getAccessibleContext().getAccessibleAction();
        return action != null && action.doAccessibleAction(0);
    }

    /** True while KVASIR's THINK LED is lit — a consult in flight. */
    public static boolean kvasirThinking() {
        RackDevice kvasir = kvasir();
        Led think = kvasir == null ? null : find(kvasir, Led.class, "THINK");
        return think != null && think.isOn();
    }

    /** Every LCD text on the KVASIR faceplate, joined — what the shot will show. */
    public static String kvasirLcds() {
        RackDevice kvasir = kvasir();
        StringBuilder sb = new StringBuilder();
        if (kvasir != null) {
            collect(kvasir, LcdDisplay.class, sb);
        }
        return sb.toString();
    }

    private static RackDevice kvasir() {
        for (RackDevice d : RackService.getDefault().getRack().getDevices()) {
            if ("KVASIR".equals(d.getTitle())) {
                return d;
            }
        }
        return null;
    }

    private static void collect(Container c, Class<LcdDisplay> type, StringBuilder sb) {
        for (Component child : c.getComponents()) {
            if (type.isInstance(child)) {
                sb.append(((LcdDisplay) child).getText()).append('\n');
            } else if (child instanceof Container cc) {
                collect(cc, type, sb);
            }
        }
    }

    /** First descendant of the type whose accessible name is {@code name} (any name when null). */
    static <T extends Component> T find(Container c, Class<T> type, String name) {
        for (Component child : c.getComponents()) {
            if (type.isInstance(child) && (name == null || name.equals(accessibleName(child)))) {
                return type.cast(child);
            }
            if (child instanceof Container cc) {
                T found = find(cc, type, name);
                if (found != null) {
                    return found;
                }
            }
        }
        return null;
    }

    private static String accessibleName(Component c) {
        javax.accessibility.AccessibleContext ctx = c.getAccessibleContext();
        return ctx == null ? null : ctx.getAccessibleName();
    }

    private static void writePatch(File dir, JSONObject patch) throws IOException {
        Files.writeString(new File(dir, RackIO.DEFAULT_FILENAME).toPath(), patch.toString(2),
                StandardCharsets.UTF_8);
    }
}
