#!/bin/sh
# docs-shots.sh — regenerate the tutorial screenshots from the real app.
#
# Boots the assembled app with -Dnmox.shots.dir set; DocsShots (ui module)
# cycles each suite tab, paints the main window into a 2x PNG per tab, and
# exits the app. Run after any UI-visible change so the docs never drift
# from the shipping product.
#
#   scripts/docs-shots.sh [output-dir] [locale]   (default: docs/images/tabs)
#
# v2.161.0: a translated document is illustrated in ITS language. Pass a
# locale as the second argument and the app boots with --locale, so every
# window paints the reader's own words (and mirrors for he/ar):
#   scripts/docs-shots.sh docs/images/he/tabs he
# NMOX_SHOTS_KEEP names the shots to keep (space-separated basenames
# without .png); the rest are deleted after the run so a language dir never
# holds a shot no document of that language references (the ImageRefsTest
# orphan law). NMOX_SHOTS_APP points at an assembled app elsewhere (a
# sibling worktree's) when this tree has none.
#
# NMOX_SHOTS_STAGED=1 (v2.162.0) adds the user guide's six hand-staged
# states — the rack front and rear, the editor, an experiment with its
# walkthrough, KVASIR explaining a failed run, the learning-space shelf —
# painted in the same locale: the app boots with a THROWAWAY user.home
# (fixtures generated by the product's own templates and presets), KVASIR
# consent seeded in the throwaway userdir, and the shelf dialog queued.
# KVASIR's diagnosis is REAL (the Messages API, answering in the reader's
# language), so the run needs CLAUDE_API_KEY/ANTHROPIC_API_KEY in the
# environment — launch from a shell that carries it; the key is never
# printed. With no key the KVASIR shot is skipped and reported MISS.
#   NMOX_SHOTS_STAGED=1 NMOX_SHOTS_NO_BUILD=1 scripts/docs-shots.sh docs/images/he he
#
# The forge OWNS its output dir — every file there is regenerable. The
# curated, hand-staged shots in docs/images/ (real DB rows, a hit
# breakpoint, a running container) are never touched by this script.
#
# Rebuilds the app first so the shots always reflect the CURRENT sources —
# a stale application/target assembly silently captures yesterday's UI
# (and, before DocsShots existed there, never exits at all). Set
# NMOX_SHOTS_NO_BUILD=1 to skip the rebuild when you know it's current.
#
# Needs a logged-in graphical session (the app paints itself — no OS
# screen-recording permission is involved). Uses a throwaway userdir AND
# cachedir so every run captures the same first-launch state and never
# contends with a running installed app's caches.
set -e
cd "$(dirname "$0")/.."

OUT="${1:-docs/images/tabs}"
LOCALE="${2:-}"
LOCALE_OPT=""
[ -n "$LOCALE" ] && LOCALE_OPT="--locale $LOCALE"
mkdir -p "$OUT"
OUT_ABS="$(cd "$OUT" && pwd)"
# docs/images holds the curated shots, and the forge both WRITES same-named
# PNGs (db-studio.png, api-studio.png…) and prunes the rest: refuse it as an
# output dir before anything boots — forge into a scratch dir and copy
IMAGES_ABS="$(cd docs/images 2>/dev/null && pwd)"
if [ "$OUT_ABS" = "$IMAGES_ABS" ]; then
  echo "refusing to forge into $OUT_ABS: it holds the curated shots — use a scratch dir and copy"
  exit 1
fi

APP="${NMOX_SHOTS_APP:-application/target/nmoxstudio/bin/nmoxstudio}"
if [ "${NMOX_SHOTS_NO_BUILD:-0}" != "1" ]; then
  echo "== assembling the app from current sources (mvn package -DskipTests) =="
  mvn -q clean package -DskipTests
fi
[ -x "$APP" ] || { echo "no assembled app at $APP"; exit 1; }

WORK="$(mktemp -d)"
UD="$WORK/shots-userdir"
CD="$WORK/shots-cachedir"
STAGED_OPTS=""
if [ "${NMOX_SHOTS_STAGED:-0}" = "1" ]; then
  # a short, readable home: the Project Studio footer and the Workbench
  # print the aimed path, and a /var/folders/... temp path reads as noise in
  # a docs picture. Deleted only when it carries this script's own marker.
  HOME_DIR="${NMOX_SHOTS_HOME:-/tmp/nmox}"
  if [ -e "$HOME_DIR" ] && [ ! -f "$HOME_DIR/.nmox-docs-home" ]; then
    echo "refusing: $HOME_DIR exists and is not a docs-shots home (no .nmox-docs-home marker)"
    exit 1
  fi
  rm -rf "$HOME_DIR"
  mkdir -p "$HOME_DIR"
  : > "$HOME_DIR/.nmox-docs-home"
  # KVASIR's consent lives in the userdir (v2.63.0); a fresh one has none
  PREFS="$UD/config/Preferences/org/nmox/NMOX/Studio"
  mkdir -p "$PREFS"
  # Claude is the provider the forge asks (David's call); the key reaches the
  # app only through an interactive shell, so the launch below runs under
  # `zsh -ilc` — ~/.zshrc is where CLAUDE_API_KEY lives and a plain exec of
  # the launcher inherits this script's non-interactive environment instead
  printf 'kvasir.external.consent=true\nkvasir.provider=anthropic\n' > "$PREFS/rack.properties"
  # the scenes' own content, in the language being painted (v2.163.0): the
  # cards on the board, the rows in the grid, the labels on the canvas
  FIXTURES="$(cd "$(dirname "$0")/.." && pwd)/docs/i18n/forge-fixtures.json"
  [ -f "$FIXTURES" ] || { echo "no forge fixtures at $FIXTURES"; exit 1; }
  # API Studio's picture is a response, so something must answer the starter
  # request's /health on loopback for the length of the run
  # (v2.164.0: and the shop front the DevTools picture picks from, which the
  # forge's own scene writes under the demo shop during the run)
  python3 "$(dirname "$0")/docs-fixture-server.py" 3000 "$HOME_DIR/NMOX/storefront/site" >/dev/null 2>&1 &
  FIXTURE_SERVER=$!
  SERVICES="$FIXTURE_SERVER"
  DOCS_CONTAINER=""
  cleanup() {
    # shellcheck disable=SC2086 — a list of pids
    kill $SERVICES 2>/dev/null || true
    [ -n "$DOCS_CONTAINER" ] && docker rm -fv "$DOCS_CONTAINER" >/dev/null 2>&1
    return 0
  }
  trap cleanup EXIT
  # v2.164.0: Contract Studio's picture is connected to a chain — a local
  # anvil for the length of the run, when this machine has one and 8545 is free
  if command -v anvil >/dev/null 2>&1 && ! lsof -nP -iTCP:8545 -sTCP:LISTEN >/dev/null 2>&1; then
    anvil --host 127.0.0.1 --port 8545 --silent >/dev/null 2>&1 &
    SERVICES="$SERVICES $!"
  else
    echo "  (no anvil, or 8545 is taken: contract-studio will be skipped)"
  fi
  # v2.164.0: the Docker Panel's picture holds one real container — and ONLY
  # that one. The app never sees the daemon directly: it talks to a read-only
  # proxy that shows only containers labelled org.nmox.docs=1, so the
  # developer's own containers can never reach a docs picture. Nothing is
  # pulled: without postgres:16-alpine already present the scene is skipped.
  DOCKER_VIEW=""
  DOCKER_SOCK="$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null | sed -n 's#^unix://##p')"
  if [ -n "$DOCKER_SOCK" ] && docker image inspect postgres:16-alpine >/dev/null 2>&1; then
    DOCS_CONTAINER=storefront-db
    if docker container inspect "$DOCS_CONTAINER" >/dev/null 2>&1; then
      if [ "$(docker container inspect -f '{{index .Config.Labels "org.nmox.docs"}}' "$DOCS_CONTAINER")" = "1" ]; then
        docker rm -fv "$DOCS_CONTAINER" >/dev/null 2>&1
      else
        echo "  (a container named $DOCS_CONTAINER exists and is not the forge's: docker-panel will be skipped)"
        DOCS_CONTAINER=""
      fi
    fi
    if [ -n "$DOCS_CONTAINER" ] && docker run -d --label org.nmox.docs=1 --name "$DOCS_CONTAINER" \
        -e POSTGRES_PASSWORD=docs-only -p 127.0.0.1::5432 postgres:16-alpine >/dev/null; then
      python3 "$(dirname "$0")/docs-docker-proxy.py" 23750 "$DOCKER_SOCK" >/dev/null 2>&1 &
      SERVICES="$SERVICES $!"
      DOCKER_VIEW="tcp://127.0.0.1:23750"
    else
      DOCS_CONTAINER=""
    fi
  else
    echo "  (no Docker daemon or no postgres:16-alpine image: docker-panel will be skipped)"
  fi
  STAGED_OPTS="-J-Duser.home=$HOME_DIR -J-Dnmox.shots.staged=1 -J-Dnmox.shots.fixtures=$FIXTURES -J-Dnmox.shots.lang=${LOCALE:-en} -J-Dnmox.shots.dialogs=File/org.nmox.studio.ui.actions.ManageLearningSpacesAction=spaces-shelf.png"
  : "${NMOX_SHOTS_KEEP:=task-rack rack-rear editor experiment-walkthrough kvasir-explain spaces-shelf task-board sprint-overview standup infra-designer db-studio api-studio presentation-mode editor-screenshot-2x docker-panel contract-studio story-06-devtools-pick debug-javascript}"
fi
echo "== booting with nmox.shots.dir=$OUT_ABS${LOCALE:+ --locale $LOCALE} (throwaway userdir + cachedir) =="
# shellcheck disable=SC2086 — a locale code and the staged flags have no spaces; unquoted on purpose
# an interactive login zsh so the app sees the keys ~/.zshrc exports; "$@"
# keeps every argument's quoting intact through the hop
# the app gets its own leash (NMOX_SHOTS_TIMEOUT seconds): a forge that stops
# advancing must still reach the log copy and the missing-shots report below —
# a timeout wrapped around the whole script killed both and hid the cause
FORGE_TIMEOUT="${NMOX_SHOTS_TIMEOUT:-900}"
# v2.164.0: the in-app Browser needs JavaFX, which a source build's host JDK
# lacks and the installed app's bundled runtime carries. NMOX_SHOTS_JDKHOME
# names a runtime; by default the installed app's is used when it has JavaFX
BUNDLED_JRE="/Applications/NMOX Studio.app/Contents/Resources/nmoxstudio/jre"
if [ -z "${NMOX_SHOTS_JDKHOME:-}" ] && [ -f "$BUNDLED_JRE/lib/javafx.properties" ]; then
  NMOX_SHOTS_JDKHOME="$BUNDLED_JRE"
fi
set --
[ -n "${NMOX_SHOTS_JDKHOME:-}" ] && set -- --jdkhome "$NMOX_SHOTS_JDKHOME"
# shellcheck disable=SC2086 — one NAME=value word or none
env ${DOCKER_VIEW:+DOCKER_HOST=$DOCKER_VIEW} \
timeout --kill-after=30 "$FORGE_TIMEOUT" \
zsh -ilc 'exec "$@"' nmox-forge \
  "$APP" --nosplash "$@" --userdir "$UD" --cachedir "$CD" $LOCALE_OPT $STAGED_OPTS \
  -J-Dnmox.shots.dir="$OUT_ABS" \
  -J-Dnmox.shots.fakerun="Run — meridian|http://localhost:3000/" \
  -J-Dplugin.manager.check.updates=false \
  -J-Dapple.awt.application.name="NMOX Studio"
boot=$?
[ "$boot" = 124 ] && echo "forge timed out after ${FORGE_TIMEOUT}s — the log below says where it stopped"

echo "== shots =="
missing=0
if [ -n "${NMOX_SHOTS_KEEP:-}" ]; then
  for png in "$OUT_ABS"/*.png; do
    base="$(basename "$png" .png)"
    case " $NMOX_SHOTS_KEEP " in
      *" $base "*) ;;
      *) rm -f "$png"; echo "  drop $base.png (not in NMOX_SHOTS_KEEP)";;
    esac
  done
fi
for f in ${NMOX_SHOTS_KEEP:-workbench the-task-rack project-studio db-studio contract-studio \
         infra-designer api-studio docker-panel block-studio \
         learning-spaces wizards-and-kits}; do
  if [ -s "$OUT_ABS/$f.png" ]; then
    echo "  ok   $f.png"
  else
    echo "  MISS $f.png"
    missing=1
  fi
done
# NMOX_SHOTS_LOG=<file> keeps the boot's messages.log (the forge's warnings —
# a skipped staged shot says why there) before the throwaway dirs go
if [ -n "${NMOX_SHOTS_LOG:-}" ] && [ -f "$UD/var/log/messages.log" ]; then
  cp "$UD/var/log/messages.log" "$NMOX_SHOTS_LOG" 2>/dev/null || true
fi
rm -rf "$WORK" 2>/dev/null || true
[ -n "${HOME_DIR:-}" ] && [ -f "$HOME_DIR/.nmox-docs-home" ] && rm -rf "$HOME_DIR"
exit $missing
