package org.nmox.studio.rack.blockstudio;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Blocks → a real Web Component, with the mapping that makes the code
 * pane a *controller*: every block records the exact character range it
 * emitted, so selecting a piece on the canvas highlights its lines and
 * the generated file reads as a projection of the block tree.
 *
 * <p>Output is one self-contained ES module: a class extending
 * HTMLElement with shadow DOM, private state fields, a render() that
 * rebuilds the template and re-wires listeners, and the
 * customElements.define call. {@code {name}} in text/expressions
 * interpolates a declared state field; everything else is escaped into
 * the template literal, so block parameters cannot break out of the
 * generated code.
 *
 * <p>The file opens with {@link #MARKER}; the save path refuses to
 * overwrite any file that lacks it (never-clobber).
 */
public final class BlockCodegen {

    /** First line of every generated file; the overwrite guard keys on it. */
    public static final String MARKER =
            "// Generated by NMOX Block Studio — re-save from the studio, edits here are overwritten.";

    /** Shape of a tag/segment; the hyphen rules are checked in code
     * (no grouped quantifiers — the find-sec-bugs ReDOS idiom). */
    private static final Pattern TAG_CHARS = Pattern.compile("[a-z][a-z0-9-]*");
    /** Plain HTML element tag (no hyphen requirement). */
    private static final Pattern HTML_TAG = Pattern.compile("[a-z][a-z0-9-]*");
    private static final Pattern IDENT = Pattern.compile("[a-z_][A-Za-z0-9_]*");
    private static final Pattern EVENT = Pattern.compile("[a-z]+");
    private static final Pattern ATTR_NAME = Pattern.compile("[a-zA-Z-][a-zA-Z0-9-]*");
    private static final Pattern OP = Pattern.compile("==|!=|>|<|>=|<=");
    private static final Pattern REF = Pattern.compile("\\{([a-z_][A-Za-z0-9_]*)}");
    private static final Pattern PROP_REF = Pattern.compile("\\{@([a-z][a-z0-9-]*)}");
    private static final Pattern PROP_NAME = Pattern.compile("[a-z][a-z0-9-]*");

    /** Generated code + per-block [start,end) character ranges. */
    public record Result(String code, Map<String, int[]> ranges) { }

    private BlockCodegen() {
    }

    /**
     * Validation before generation: every problem a block tree can have,
     * as human sentences. Empty means {@link #generate} will succeed.
     */
    public static List<String> validate(BlockDoc doc) {
        List<String> problems = new ArrayList<>();
        String tag = doc.root().param("tag");
        if (!validTag(tag)) {
            problems.add("Component tag \"" + tag
                    + "\" must be lowercase and contain a hyphen (custom-element rule), e.g. my-widget");
        }
        List<String> states = stateNames(doc);
        for (Block b : doc.preorder()) {
            for (Map.Entry<String, String> p : b.params().entrySet()) {
                // params are one-line by construction in the UI; a hand-edited
                // workspace can smuggle newlines that would split a generated
                // line (invalid JS inside quoted literals, unparseable
                // template lines) — refuse them all at the source
                if (p.getValue().indexOf('\n') >= 0 || p.getValue().indexOf('\r') >= 0) {
                    problems.add(b.kind().display() + " " + p.getKey()
                            + " must be a single line");
                }
            }
            switch (b.kind()) {
                case STATE -> {
                    if (!IDENT.matcher(b.param("name")).matches()) {
                        problems.add("State name \"" + b.param("name") + "\" is not a valid identifier");
                    }
                    if (leadingZero(b.param("initial"))) {
                        problems.add("State initial \"" + b.param("initial")
                                + "\" has a leading zero (a syntax error in JS modules)");
                    }
                }
                case PROP -> {
                    if (!PROP_NAME.matcher(b.param("name")).matches()
                            || b.param("name").contains("--") || b.param("name").endsWith("-")) {
                        problems.add("Prop name \"" + b.param("name")
                                + "\" must be a lowercase attribute name (dashes allowed), e.g. label or data-role");
                    }
                }
                case ELEMENT -> {
                    if (!HTML_TAG.matcher(b.param("tag")).matches()) {
                        problems.add("Element tag \"" + b.param("tag") + "\" is not a valid HTML tag");
                    }
                }
                case TEXT -> {
                    // a leading space survives entity-escaping verbatim and
                    // the parser's TEXT branch refuses indented-looking
                    // lines — generate would write a file Open Component
                    // could never read back (the v1.89.0 review's find)
                    if (b.param("text").startsWith(" ")) {
                        problems.add("Text must not start with a space"
                                + " (it would be invisible in HTML anyway)");
                    }
                }
                case SET_ATTR -> {
                    if (!ATTR_NAME.matcher(b.param("name")).matches()) {
                        problems.add("Attribute name \"" + b.param("name") + "\" is not valid");
                    } else if (b.param("name").equals("data-b")) {
                        // the generator's own anchor attribute — a user copy
                        // would be hijacked as the element id on re-import
                        problems.add("Attribute name \"data-b\" is reserved by Block Studio (it anchors listeners)");
                    }
                }
                case ON_EVENT -> {
                    if (!EVENT.matcher(b.param("event")).matches()) {
                        problems.add("Event \"" + b.param("event") + "\" is not a valid event name");
                    }
                }
                case SET_STATE, IF_STATE -> {
                    if (b.kind() == BlockKind.SET_STATE && exprProblem(b.param("expr")) != null) {
                        problems.add(exprProblem(b.param("expr")));
                    }
                    if (!states.contains(b.param("name"))) {
                        problems.add(b.kind().display() + " refers to undeclared state \""
                                + b.param("name") + "\"");
                    }
                    if (b.kind() == BlockKind.IF_STATE && !OP.matcher(b.param("op")).matches()) {
                        problems.add("If-state operator \"" + b.param("op") + "\" is not one of == != > < >= <=");
                    }
                }
                case TOGGLE_CLASS -> {
                    if (!ATTR_NAME.matcher(b.param("class")).matches()) {
                        problems.add("Class \"" + b.param("class") + "\" is not a valid class name");
                    }
                }
                case SLOT -> {
                    String slotName = b.param("name");
                    if (!slotName.isEmpty() && !ATTR_NAME.matcher(slotName).matches()) {
                        problems.add("Slot name \"" + slotName + "\" is not valid");
                    }
                }
                case TIMER -> {
                    // length cap before parse: a 20-digit "number" passes the
                    // regex but overflows Long.parseLong (the v1.82.0 review's
                    // EDT crash from a plain text field)
                    String ms = b.param("ms");
                    if (!ms.matches("[0-9]+") || ms.length() > 9 || Long.parseLong(ms) < 50) {
                        problems.add("Timer interval \"" + ms
                                + "\" must be a whole number of milliseconds (min 50, max 9 digits)");
                    }
                }
                case DISPATCH -> {
                    if (!TAG_CHARS.matcher(b.param("event")).matches()) {
                        problems.add("Dispatch event \"" + b.param("event")
                                + "\" must be lowercase (dashes allowed), e.g. count-changed");
                    }
                }
                default -> { }
            }
        }
        return problems;
    }

    /** The expr() residue rule as a validate()-time problem, or null when fine. */
    static String exprProblem(String raw) {
        String residue = PROP_REF.matcher(REF.matcher(raw).replaceAll("0")).replaceAll("0");
        if (!residue.matches("[0-9+\\-*/%().'\\sA-Za-z\"_]*") || residue.contains("`")) {
            return "Expression \"" + raw + "\" contains unsupported characters"
                    + " (allowed: numbers, + - * / % ( ), quotes, {state} references)";
        }
        return null;
    }

    /** "01" / "-01" style number literals are module syntax errors. */
    static boolean leadingZero(String raw) {
        String n = raw.startsWith("-") ? raw.substring(1) : raw;
        return n.matches("0[0-9]+") || n.matches("0[0-9]*\\.[0-9]+");
    }

    /** Custom-element tag law: lowercase, a hyphen, no empty segments. */
    static boolean validTag(String tag) {
        return TAG_CHARS.matcher(tag).matches()
                && tag.contains("-") && !tag.contains("--") && !tag.endsWith("-");
    }

    private static List<String> propNames(BlockDoc doc) {
        List<String> names = new ArrayList<>();
        for (Block b : doc.root().children()) {
            if (b.kind() == BlockKind.PROP) {
                names.add(b.param("name"));
            }
        }
        return names;
    }

    /** label → #prop_label(); data-role → #prop_data_role(). */
    static String propAccessor(String name) {
        return "#prop_" + name.replace('-', '_');
    }

    private static List<String> stateNames(BlockDoc doc) {
        List<String> names = new ArrayList<>();
        for (Block b : doc.root().children()) {
            if (b.kind() == BlockKind.STATE) {
                names.add(b.param("name"));
            }
        }
        return names;
    }

    /** Generates; call {@link #validate} first — problems throw here. */
    public static Result generate(BlockDoc doc) {
        List<String> problems = validate(doc);
        if (!problems.isEmpty()) {
            throw new IllegalArgumentException(problems.get(0));
        }
        Emitter e = new Emitter();
        List<String> states = stateNames(doc);
        List<String> props = propNames(doc);
        String tag = doc.root().param("tag");
        String cls = className(tag);

        e.open(doc.root());
        e.line(MARKER);
        e.line("");
        e.line("class " + cls + " extends HTMLElement {");
        for (Block b : doc.root().children()) {
            if (b.kind() == BlockKind.STATE) {
                e.open(b);
                e.line("  #" + b.param("name") + " = " + literal(b.param("initial")) + ";");
                e.close(b);
            }
        }
        for (Block b : doc.root().children()) {
            if (b.kind() == BlockKind.PROP) {
                e.open(b);
                e.line("  " + propAccessor(b.param("name")) + "() { return this.getAttribute('"
                        + b.param("name") + "') ?? " + literal(b.param("default")) + "; }");
                e.close(b);
            }
        }
        if (!props.isEmpty()) {
            StringBuilder list = new StringBuilder();
            for (String p : props) {
                if (list.length() > 0) {
                    list.append(", ");
                }
                list.append("'").append(p).append("'");
            }
            e.line("  static get observedAttributes() { return [" + list + "]; }");
        }
        e.line("");
        e.line("  constructor() {");
        e.line("    super();");
        e.line("    this.attachShadow({ mode: 'open' });");
        e.line("    this.render();");
        e.line("  }");
        if (!props.isEmpty()) {
            e.line("");
            e.line("  attributeChangedCallback() {");
            e.line("    this.render();");
            e.line("  }");
        }
        e.line("");
        e.line("  render() {");
        e.line("    this.shadowRoot.innerHTML = `");
        for (Block b : doc.root().children()) {
            if (b.kind() != BlockKind.STATE) {
                emitNode(e, b, states, props, "      ");
            }
        }
        e.line("    `;");
        // listener order is CANONICAL: for each host in template preorder,
        // that host's ON_EVENT children in child order. The parser rebuilds
        // listeners as trailing children per host in code order, so THIS
        // order — unlike raw doc-preorder, which interleaves a host's
        // later listeners with its descendants' — survives the round trip
        // byte for byte (the v1.82.0 review's reorder finding).
        for (Block host : doc.preorder()) {
            if (host.kind() != BlockKind.ON_EVENT) {
                for (Block b : host.children()) {
                    if (b.kind() == BlockKind.ON_EVENT) {
                        emitListener(e, b, doc, states, props);
                    }
                }
            }
        }
        e.line("  }");
        List<Block> timers = doc.root().children().stream()
                .filter(b -> b.kind() == BlockKind.TIMER).toList();
        if (!timers.isEmpty()) {
            e.line("");
            e.line("  connectedCallback() {");
            int i = 0;
            for (Block t : timers) {
                e.open(t);
                e.line("    this._t" + i + " = setInterval(() => {");
                // a timer has no listening element — TOGGLE_CLASS et al.
                // act on the host component itself
                boolean rerender = emitActions(e, t.children(), "this", states, props, "      ");
                if (rerender) {
                    e.line("      this.render();");
                }
                e.line("    }, " + t.param("ms") + ");");
                e.close(t);
                i++;
            }
            e.line("  }");
            e.line("");
            e.line("  disconnectedCallback() {");
            for (int j = 0; j < timers.size(); j++) {
                e.line("    clearInterval(this._t" + j + ");");
            }
            e.line("  }");
        }
        e.line("}");
        e.line("");
        e.line("customElements.define('" + tag + "', " + cls + ");");
        e.close(doc.root());
        return new Result(e.code(), e.ranges());
    }

    /** my-cool-widget → MyCoolWidget. */
    static String className(String tag) {
        StringBuilder sb = new StringBuilder();
        for (String part : tag.split("-")) {
            if (!part.isEmpty()) {
                sb.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        return sb.toString();
    }

    // ---- template ----

    private static void emitNode(Emitter e, Block b, List<String> states, List<String> props, String indent) {
        switch (b.kind()) {
            case TEXT -> {
                e.open(b);
                // a TEXT piece is literal text: & and < are HTML-escaped so
                // the browser shows the characters (an Element piece is how
                // you make markup) AND so the template line can never start
                // with < — which the parser reads as markup (the old
                // documented one-way limitation, closed in v1.88.0)
                e.line(indent + interpolate(textEscape(b.param("text")), states, props));
                e.close(b);
            }
            case SLOT -> {
                e.open(b);
                String slotName = b.param("name");
                e.line(indent + (slotName.isEmpty() ? "<slot></slot>"
                        : "<slot name=\"" + attr(slotName, states, props) + "\"></slot>"));
                e.close(b);
            }
            case ELEMENT -> {
                e.open(b);
                StringBuilder openTag = new StringBuilder(indent + "<" + b.param("tag"));
                if (hasListener(b)) {
                    openTag.append(" data-b=\"").append(b.id()).append("\"");
                }
                for (Block c : b.children()) {
                    if (c.kind() == BlockKind.SET_ATTR) {
                        openTag.append(" ").append(c.param("name"))
                                .append("=\"").append(attr(c.param("value"), states, props)).append("\"");
                    } else if (c.kind() == BlockKind.STYLE) {
                        openTag.append(" style=\"").append(attr(c.param("css"), states, props)).append("\"");
                    }
                }
                openTag.append(">");
                e.line(openTag.toString());
                for (Block c : b.children()) {
                    if (c.kind() == BlockKind.ELEMENT || c.kind() == BlockKind.TEXT
                            || c.kind() == BlockKind.SLOT) {
                        emitNode(e, c, states, props, indent + "  ");
                    }
                }
                e.line(indent + "</" + b.param("tag") + ">");
                e.close(b);
            }
            default -> { }
        }
    }

    private static boolean hasListener(Block element) {
        return element.children().stream().anyMatch(c -> c.kind() == BlockKind.ON_EVENT);
    }

    // ---- listeners ----

    private static void emitListener(Emitter e, Block onEvent, BlockDoc doc, List<String> states, List<String> props) {
        Block host = doc.parentOf(onEvent.id());
        e.open(onEvent);
        String var = onEvent.id();
        e.line("    const " + var + " = this.shadowRoot.querySelector('[data-b=\""
                + host.id() + "\"]');");
        e.line("    " + var + ".addEventListener('" + onEvent.param("event") + "', () => {");
        boolean rerender = emitActions(e, onEvent.children(), var, states, props, "      ");
        if (rerender) {
            e.line("      this.render();");
        }
        e.line("    });");
        e.close(onEvent);
    }

    /** Emits actions; true when any SET_STATE ran (a re-render is due). */
    private static boolean emitActions(Emitter e, List<Block> actions, String hostVar,
            List<String> states, List<String> props, String indent) {
        boolean rerender = false;
        for (Block a : actions) {
            switch (a.kind()) {
                case SET_STATE -> {
                    e.open(a);
                    e.line(indent + "this.#" + a.param("name") + " = "
                            + expr(a.param("expr"), states, props) + ";");
                    e.close(a);
                    rerender = true;
                }
                case TOGGLE_CLASS -> {
                    e.open(a);
                    e.line(indent + hostVar + ".classList.toggle('" + a.param("class") + "');");
                    e.close(a);
                }
                case LOG -> {
                    e.open(a);
                    e.line(indent + "console.log(`" + tpl(a.param("message"), states, props) + "`);");
                    e.close(a);
                }
                case IF_STATE -> {
                    e.open(a);
                    e.line(indent + "if (this.#" + a.param("name") + " " + a.param("op") + " "
                            + literal(a.param("value")) + ") {");
                    rerender |= emitActions(e, a.children(), hostVar, states, props, indent + "  ");
                    e.line(indent + "}");
                    e.close(a);
                }
                case DISPATCH -> {
                    e.open(a);
                    e.line(indent + "this.dispatchEvent(new CustomEvent('" + a.param("event")
                            + "', { bubbles: true, composed: true, detail: `"
                            + tpl(a.param("detail"), states, props) + "` }));");
                    e.close(a);
                }
                default -> { }
            }
        }
        return rerender;
    }

    // ---- escaping & interpolation (parameters can never break out) ----

    /** Template-literal body: escape, then {state}/{@prop} interpolate. */
    static String interpolate(String text, List<String> states, List<String> props) {
        return propReplace(refReplace(tplEscape(text), states, "${this.#", "}"),
                props, "${this.", "()}");
    }

    /** Attribute value inside the template literal: also quote-safe. */
    static String attr(String text, List<String> states, List<String> props) {
        return propReplace(refReplace(tplEscape(text).replace("\"", "&quot;"),
                states, "${this.#", "}"), props, "${this.", "()}");
    }

    /** console.log template body. */
    static String tpl(String text, List<String> states, List<String> props) {
        return propReplace(refReplace(tplEscape(text), states, "${this.#", "}"),
                props, "${this.", "()}");
    }

    /** Right-hand expression: {state}/{@prop} read fields, rest validated. */
    static String expr(String raw, List<String> states, List<String> props) {
        String replaced = propReplace(refReplace(raw, states, "this.#", ""),
                props, "this.", "()");
        String problem = exprProblem(raw);
        if (problem != null) {
            throw new IllegalArgumentException(problem);
        }
        return replaced;
    }

    /** {@name} → pre + #prop_name + post for DECLARED props only. */
    private static String propReplace(String s, List<String> props, String pre, String post) {
        Matcher m = PROP_REF.matcher(s);
        StringBuilder sb = new StringBuilder();
        while (m.find()) {
            String name = m.group(1);
            m.appendReplacement(sb, Matcher.quoteReplacement(
                    props.contains(name) ? pre + propAccessor(name) + post : m.group(0)));
        }
        m.appendTail(sb);
        return sb.toString();
    }

    /** Initial values / comparison literals: number or quoted string. */
    static String literal(String raw) {
        if (raw.matches("-?[0-9]+") || raw.matches("-?[0-9]+\\.[0-9]+") || raw.equals("true") || raw.equals("false")) {
            return raw;
        }
        return "'" + raw.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }

    private static String tplEscape(String s) {
        return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${");
    }

    /**
     * HTML-escapes a TEXT piece's content ({@code &} first, so the pair
     * is reversible); {@link BlockParser} applies the exact inverse on
     * TEXT template lines. Order matters on both sides.
     */
    static String textEscape(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;");
    }

    private static String refReplace(String s, List<String> states, String pre, String post) {
        Matcher m = REF.matcher(s);
        StringBuilder sb = new StringBuilder();
        while (m.find()) {
            String name = m.group(1);
            m.appendReplacement(sb, Matcher.quoteReplacement(
                    states.contains(name) ? pre + name + post : m.group(0)));
        }
        m.appendTail(sb);
        return sb.toString();
    }

    /** StringBuilder with an open/close range recorder per block. */
    private static final class Emitter {

        private final StringBuilder sb = new StringBuilder();
        private final Map<String, Integer> openAt = new LinkedHashMap<>();
        private final Map<String, int[]> ranges = new LinkedHashMap<>();

        void open(Block b) {
            openAt.put(b.id(), sb.length());
        }

        void close(Block b) {
            ranges.put(b.id(), new int[]{openAt.remove(b.id()), sb.length()});
        }

        void line(String s) {
            sb.append(s).append('\n');
        }

        String code() {
            return sb.toString();
        }

        Map<String, int[]> ranges() {
            return ranges;
        }
    }
}
