package org.nmox.studio.rack.blockstudio;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Blocks → a real Web Component, with the mapping that makes the code
 * pane a *controller*: every block records the exact character range it
 * emitted, so selecting a piece on the canvas highlights its lines and
 * the generated file reads as a projection of the block tree.
 *
 * <p>Output is one self-contained ES module: a class extending
 * HTMLElement with shadow DOM, private state fields, a render() that
 * rebuilds the template and re-wires listeners, and the
 * customElements.define call. {@code {name}} in text/expressions
 * interpolates a declared state field; everything else is escaped into
 * the template literal, so block parameters cannot break out of the
 * generated code.
 *
 * <p>The file opens with {@link #MARKER}; the save path refuses to
 * overwrite any file that lacks it (never-clobber).
 */
public final class BlockCodegen {

    /** First line of every generated file; the overwrite guard keys on it. */
    public static final String MARKER =
            "// Generated by NMOX Block Studio — re-save from the studio, edits here are overwritten.";

    /** Shape of a tag/segment; the hyphen rules are checked in code
     * (no grouped quantifiers — the find-sec-bugs ReDOS idiom). */
    private static final Pattern TAG_CHARS = Pattern.compile("[a-z][a-z0-9-]*");
    /** Plain HTML element tag (no hyphen requirement). */
    private static final Pattern HTML_TAG = Pattern.compile("[a-z][a-z0-9-]*");
    private static final Pattern IDENT = Pattern.compile("[a-z_][A-Za-z0-9_]*");
    private static final Pattern EVENT = Pattern.compile("[a-z]+");
    private static final Pattern ATTR_NAME = Pattern.compile("[a-zA-Z-][a-zA-Z0-9-]*");
    private static final Pattern OP = Pattern.compile("==|!=|>|<|>=|<=");
    private static final Pattern REF = Pattern.compile("\\{([a-z_][A-Za-z0-9_]*)}");

    /** Generated code + per-block [start,end) character ranges. */
    public record Result(String code, Map<String, int[]> ranges) { }

    private BlockCodegen() {
    }

    /**
     * Validation before generation: every problem a block tree can have,
     * as human sentences. Empty means {@link #generate} will succeed.
     */
    public static List<String> validate(BlockDoc doc) {
        List<String> problems = new ArrayList<>();
        String tag = doc.root().param("tag");
        if (!validTag(tag)) {
            problems.add("Component tag \"" + tag
                    + "\" must be lowercase and contain a hyphen (custom-element rule), e.g. my-widget");
        }
        List<String> states = stateNames(doc);
        for (Block b : doc.preorder()) {
            switch (b.kind()) {
                case STATE -> {
                    if (!IDENT.matcher(b.param("name")).matches()) {
                        problems.add("State name \"" + b.param("name") + "\" is not a valid identifier");
                    }
                }
                case ELEMENT -> {
                    if (!HTML_TAG.matcher(b.param("tag")).matches()) {
                        problems.add("Element tag \"" + b.param("tag") + "\" is not a valid HTML tag");
                    }
                }
                case SET_ATTR -> {
                    if (!ATTR_NAME.matcher(b.param("name")).matches()) {
                        problems.add("Attribute name \"" + b.param("name") + "\" is not valid");
                    }
                }
                case ON_EVENT -> {
                    if (!EVENT.matcher(b.param("event")).matches()) {
                        problems.add("Event \"" + b.param("event") + "\" is not a valid event name");
                    }
                }
                case SET_STATE, IF_STATE -> {
                    if (!states.contains(b.param("name"))) {
                        problems.add(b.kind().display() + " refers to undeclared state \""
                                + b.param("name") + "\"");
                    }
                    if (b.kind() == BlockKind.IF_STATE && !OP.matcher(b.param("op")).matches()) {
                        problems.add("If-state operator \"" + b.param("op") + "\" is not one of == != > < >= <=");
                    }
                }
                case TOGGLE_CLASS -> {
                    if (!ATTR_NAME.matcher(b.param("class")).matches()) {
                        problems.add("Class \"" + b.param("class") + "\" is not a valid class name");
                    }
                }
                case SLOT -> {
                    String slotName = b.param("name");
                    if (!slotName.isEmpty() && !ATTR_NAME.matcher(slotName).matches()) {
                        problems.add("Slot name \"" + slotName + "\" is not valid");
                    }
                }
                case TIMER -> {
                    if (!b.param("ms").matches("[0-9]+") || Long.parseLong(b.param("ms")) < 50) {
                        problems.add("Timer interval \"" + b.param("ms")
                                + "\" must be a whole number of milliseconds (min 50)");
                    }
                }
                case DISPATCH -> {
                    if (!TAG_CHARS.matcher(b.param("event")).matches()) {
                        problems.add("Dispatch event \"" + b.param("event")
                                + "\" must be lowercase (dashes allowed), e.g. count-changed");
                    }
                }
                default -> { }
            }
        }
        return problems;
    }

    /** Custom-element tag law: lowercase, a hyphen, no empty segments. */
    static boolean validTag(String tag) {
        return TAG_CHARS.matcher(tag).matches()
                && tag.contains("-") && !tag.contains("--") && !tag.endsWith("-");
    }

    private static List<String> stateNames(BlockDoc doc) {
        List<String> names = new ArrayList<>();
        for (Block b : doc.root().children()) {
            if (b.kind() == BlockKind.STATE) {
                names.add(b.param("name"));
            }
        }
        return names;
    }

    /** Generates; call {@link #validate} first — problems throw here. */
    public static Result generate(BlockDoc doc) {
        List<String> problems = validate(doc);
        if (!problems.isEmpty()) {
            throw new IllegalArgumentException(problems.get(0));
        }
        Emitter e = new Emitter();
        List<String> states = stateNames(doc);
        String tag = doc.root().param("tag");
        String cls = className(tag);

        e.open(doc.root());
        e.line(MARKER);
        e.line("");
        e.line("class " + cls + " extends HTMLElement {");
        for (Block b : doc.root().children()) {
            if (b.kind() == BlockKind.STATE) {
                e.open(b);
                e.line("  #" + b.param("name") + " = " + literal(b.param("initial")) + ";");
                e.close(b);
            }
        }
        e.line("");
        e.line("  constructor() {");
        e.line("    super();");
        e.line("    this.attachShadow({ mode: 'open' });");
        e.line("    this.render();");
        e.line("  }");
        e.line("");
        e.line("  render() {");
        e.line("    this.shadowRoot.innerHTML = `");
        for (Block b : doc.root().children()) {
            if (b.kind() != BlockKind.STATE) {
                emitNode(e, b, states, "      ");
            }
        }
        e.line("    `;");
        for (Block b : doc.preorder()) {
            if (b.kind() == BlockKind.ON_EVENT) {
                emitListener(e, b, doc, states);
            }
        }
        e.line("  }");
        List<Block> timers = doc.root().children().stream()
                .filter(b -> b.kind() == BlockKind.TIMER).toList();
        if (!timers.isEmpty()) {
            e.line("");
            e.line("  connectedCallback() {");
            int i = 0;
            for (Block t : timers) {
                e.open(t);
                e.line("    this._t" + i + " = setInterval(() => {");
                // a timer has no listening element — TOGGLE_CLASS et al.
                // act on the host component itself
                boolean rerender = emitActions(e, t.children(), "this", states, "      ");
                if (rerender) {
                    e.line("      this.render();");
                }
                e.line("    }, " + t.param("ms") + ");");
                e.close(t);
                i++;
            }
            e.line("  }");
            e.line("");
            e.line("  disconnectedCallback() {");
            for (int j = 0; j < timers.size(); j++) {
                e.line("    clearInterval(this._t" + j + ");");
            }
            e.line("  }");
        }
        e.line("}");
        e.line("");
        e.line("customElements.define('" + tag + "', " + cls + ");");
        e.close(doc.root());
        return new Result(e.code(), e.ranges());
    }

    /** my-cool-widget → MyCoolWidget. */
    static String className(String tag) {
        StringBuilder sb = new StringBuilder();
        for (String part : tag.split("-")) {
            if (!part.isEmpty()) {
                sb.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        return sb.toString();
    }

    // ---- template ----

    private static void emitNode(Emitter e, Block b, List<String> states, String indent) {
        switch (b.kind()) {
            case TEXT -> {
                e.open(b);
                e.line(indent + interpolate(b.param("text"), states));
                e.close(b);
            }
            case SLOT -> {
                e.open(b);
                String slotName = b.param("name");
                e.line(indent + (slotName.isEmpty() ? "<slot></slot>"
                        : "<slot name=\"" + attr(slotName, states) + "\"></slot>"));
                e.close(b);
            }
            case ELEMENT -> {
                e.open(b);
                StringBuilder openTag = new StringBuilder(indent + "<" + b.param("tag"));
                if (hasListener(b)) {
                    openTag.append(" data-b=\"").append(b.id()).append("\"");
                }
                for (Block c : b.children()) {
                    if (c.kind() == BlockKind.SET_ATTR) {
                        openTag.append(" ").append(c.param("name"))
                                .append("=\"").append(attr(c.param("value"), states)).append("\"");
                    } else if (c.kind() == BlockKind.STYLE) {
                        openTag.append(" style=\"").append(attr(c.param("css"), states)).append("\"");
                    }
                }
                openTag.append(">");
                e.line(openTag.toString());
                for (Block c : b.children()) {
                    if (c.kind() == BlockKind.ELEMENT || c.kind() == BlockKind.TEXT
                            || c.kind() == BlockKind.SLOT) {
                        emitNode(e, c, states, indent + "  ");
                    }
                }
                e.line(indent + "</" + b.param("tag") + ">");
                e.close(b);
            }
            default -> { }
        }
    }

    private static boolean hasListener(Block element) {
        return element.children().stream().anyMatch(c -> c.kind() == BlockKind.ON_EVENT);
    }

    // ---- listeners ----

    private static void emitListener(Emitter e, Block onEvent, BlockDoc doc, List<String> states) {
        Block host = doc.parentOf(onEvent.id());
        e.open(onEvent);
        String var = onEvent.id();
        e.line("    const " + var + " = this.shadowRoot.querySelector('[data-b=\""
                + host.id() + "\"]');");
        e.line("    " + var + ".addEventListener('" + onEvent.param("event") + "', () => {");
        boolean rerender = emitActions(e, onEvent.children(), var, states, "      ");
        if (rerender) {
            e.line("      this.render();");
        }
        e.line("    });");
        e.close(onEvent);
    }

    /** Emits actions; true when any SET_STATE ran (a re-render is due). */
    private static boolean emitActions(Emitter e, List<Block> actions, String hostVar,
            List<String> states, String indent) {
        boolean rerender = false;
        for (Block a : actions) {
            switch (a.kind()) {
                case SET_STATE -> {
                    e.open(a);
                    e.line(indent + "this.#" + a.param("name") + " = "
                            + expr(a.param("expr"), states) + ";");
                    e.close(a);
                    rerender = true;
                }
                case TOGGLE_CLASS -> {
                    e.open(a);
                    e.line(indent + hostVar + ".classList.toggle('" + a.param("class") + "');");
                    e.close(a);
                }
                case LOG -> {
                    e.open(a);
                    e.line(indent + "console.log(`" + tpl(a.param("message"), states) + "`);");
                    e.close(a);
                }
                case IF_STATE -> {
                    e.open(a);
                    e.line(indent + "if (this.#" + a.param("name") + " " + a.param("op") + " "
                            + literal(a.param("value")) + ") {");
                    rerender |= emitActions(e, a.children(), hostVar, states, indent + "  ");
                    e.line(indent + "}");
                    e.close(a);
                }
                case DISPATCH -> {
                    e.open(a);
                    e.line(indent + "this.dispatchEvent(new CustomEvent('" + a.param("event")
                            + "', { bubbles: true, composed: true, detail: `"
                            + tpl(a.param("detail"), states) + "` }));");
                    e.close(a);
                }
                default -> { }
            }
        }
        return rerender;
    }

    // ---- escaping & interpolation (parameters can never break out) ----

    /** Template-literal body: escape, then {state} → ${this.#state}. */
    static String interpolate(String text, List<String> states) {
        return refReplace(tplEscape(text), states, "${this.#", "}");
    }

    /** Attribute value inside the template literal: also quote-safe. */
    static String attr(String text, List<String> states) {
        return refReplace(tplEscape(text).replace("\"", "&quot;"), states, "${this.#", "}");
    }

    /** console.log template body. */
    static String tpl(String text, List<String> states) {
        return refReplace(tplEscape(text), states, "${this.#", "}");
    }

    /** Right-hand expression: {state} → this.#state, rest validated. */
    static String expr(String raw, List<String> states) {
        String replaced = refReplace(raw, states, "this.#", "");
        // whatever remains outside references must be arithmetic-safe
        String residue = REF.matcher(raw).replaceAll("0");
        if (!residue.matches("[0-9+\\-*/%().'\\sA-Za-z\"_]*") || residue.contains("`")) {
            throw new IllegalArgumentException("Expression \"" + raw + "\" contains unsupported characters");
        }
        return replaced;
    }

    /** Initial values / comparison literals: number or quoted string. */
    static String literal(String raw) {
        if (raw.matches("-?[0-9]+") || raw.matches("-?[0-9]+\\.[0-9]+") || raw.equals("true") || raw.equals("false")) {
            return raw;
        }
        return "'" + raw.replace("\\", "\\\\").replace("'", "\\'") + "'";
    }

    private static String tplEscape(String s) {
        return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${");
    }

    private static String refReplace(String s, List<String> states, String pre, String post) {
        Matcher m = REF.matcher(s);
        StringBuilder sb = new StringBuilder();
        while (m.find()) {
            String name = m.group(1);
            m.appendReplacement(sb, Matcher.quoteReplacement(
                    states.contains(name) ? pre + name + post : m.group(0)));
        }
        m.appendTail(sb);
        return sb.toString();
    }

    /** StringBuilder with an open/close range recorder per block. */
    private static final class Emitter {

        private final StringBuilder sb = new StringBuilder();
        private final Map<String, Integer> openAt = new LinkedHashMap<>();
        private final Map<String, int[]> ranges = new LinkedHashMap<>();

        void open(Block b) {
            openAt.put(b.id(), sb.length());
        }

        void close(Block b) {
            ranges.put(b.id(), new int[]{openAt.remove(b.id()), sb.length()});
        }

        void line(String s) {
            sb.append(s).append('\n');
        }

        String code() {
            return sb.toString();
        }

        Map<String, int[]> ranges() {
            return ranges;
        }
    }
}
